---
sidebar: sidebar 
permalink: scpivs44_access_reports.html 
keywords:  
summary: 1 つ以上のジョブのレポートをダッシュボードから要求できます。 
---
= レポートにアクセスする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
1 つ以上のジョブのレポートをダッシュボードから要求できます。

［ レポート ］ タブには、ダッシュボードの ［ ジョブ ］ ページで選択したジョブに関する情報が表示されます。ジョブが選択されていない場合、 [ レポート ] タブは空白になります。

.手順
. vCenterクライアントのショートカットページで、SnapCenter Plug-in for VMware vSphere（SCV）を選択します。
. SCVの左側のナビゲーションペインで、*[ダッシュボード]*>*[レポート]*タブを選択します。
. バックアップレポートでは、次の操作を実行できます。
+
.. レポートを変更します
+
フィルタアイコンを選択して、期間、ジョブステータスタイプ、リソースグループ、およびレポートに含めるポリシーを変更します。

.. 詳細レポートを生成します
+
任意のジョブをダブルクリックして、そのジョブの詳細レポートを生成します。



. オプション： ［ レポート ］ タブで、 ［ * ダウンロード * ］ をクリックし、形式（ HTML または CSV ）を選択します。
+
ダウンロードアイコンをクリックしてプラグインのログをダウンロードすることもできます。





== VMware vSphere Clientからのレポートのタイプ

VMware vSphere Client for SnapCenter にはカスタマイズ可能なレポートオプションが用意されており、データ保護ジョブやプラグインリソースのステータスに関する詳細を確認できます。レポートを生成できるのはプライマリ保護のみです。


NOTE: バックアップスケジュールは、SnapCenter Plug-in for VMware vSphereが導入されているタイムゾーンで実行されます。 vCenterでは、vCenterが配置されているタイムゾーンのデータが報告されます。そのため、SnapCenter Plug-in for VMware vSphereとvCenterが異なるタイムゾーンにある場合は、VMware vSphereクライアントのダッシュボードのデータがレポートのデータと同じでない可能性があります。

ダッシュボードには、移行後のバックアップの実行後に、移行済みのバックアップに関する情報が表示されます。

|===
| レポートタイプ | 説明 


| バックアップレポート | バックアップジョブに関する概要データを表示します。グラフ上のセクション / ステータスをクリックすると、そのステータスのジョブのリストが ［ * レポート * ］ タブに表示されます。

各ジョブについて、ジョブID、対応するリソースグループ、バックアップポリシー、開始時間と期間、ステータス、およびジョブの詳細が表示されます。ジョブが完了した場合はジョブ名（Snapshot名）、警告またはエラーメッセージが表示されます。

レポートテーブルは、 HTML 形式または CSV 形式でダウンロードできます。また、（レポートのジョブだけでなく）すべてのジョブのジョブ監視ジョブログもダウンロードできます。
削除されたバックアップはレポートに含まれません。 


| マウントレポート | マウントジョブに関する概要データを表示します。グラフ上のセクション / ステータスをクリックすると、そのステータスのジョブのリストが [ レポート ] タブに表示されます。

レポートには、各ジョブについて、ジョブ ID 、ジョブステータス、ジョブ名、およびジョブの開始時刻と終了時刻が表示されます。ジョブ名にはSnapshot名が含まれています。

例： `Mount Backup <snapshot-copy-name>`

レポートテーブルは、 HTML 形式または CSV 形式でダウンロードできます。

また、（レポートのジョブだけでなく）すべてのジョブのジョブ監視ジョブログもダウンロードできます。 


| リストアレポート | リストアジョブに関する概要ステータス情報を表示します。グラフ上のセクション / ステータスをクリックすると、そのステータスのジョブのリストが [ レポート ] タブに表示されます。
レポートには、各ジョブについて、ジョブ ID 、ジョブステータス、ジョブ名、およびジョブの開始時刻と終了時刻が表示されます。ジョブ名にはSnapshot名が含まれています。例： `Restore Backup <snapshot-copy-name>`

レポートテーブルは、 HTML 形式または CSV 形式でダウンロードできます。また、（レポートのジョブだけでなく）すべてのジョブのジョブ監視ジョブログもダウンロードできます。 


| 『 Last Protection Status of VM or Datastores 』レポート | SnapCenter Plug-in for VMware vSphereで管理されているVMとデータストアについて、指定された日数における保護ステータスに関する概要情報が表示されます。デフォルトは7日です。プロパティファイルの値を変更するには、を参照してください link:scpivs44_modify_configuration_default_values.html["設定のデフォルト値を変更します"]。プライマリ保護グラフでセクション / ステータスをクリックすると、そのステータスの VM またはデータストアのリストが * Reports * タブに表示されます。保護されているVMとデータストアの[VM or Datastores Protection Status Report]には、設定された日数内にバックアップされたVMまたはデータストアの名前、最新のSnapshot名、および最新のバックアップ実行の開始時刻と終了時刻が表示されます。保護されていないVMまたはデータストアの[VM or Datastores Protection Status Report]には、設定された日数内にバックアップが完了していないVMまたはデータストアの名前が表示されます。レポートテーブルは、HTML形式またはCSV形式でダウンロードできます。レポート内のジョブだけでなく、すべてのジョブのジョブモニタジョブログをダウンロードすることもできます。このレポートは、プラグインのキャッシュが更新されると1時間ごとに更新されます。そのため、最近バックアップされたVMまたはデータストアが表示されないことがあります。 
|===