---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: バックアップリソースグループを作成、変更、削除したり、リソースグループに対してバックアップ処理を実行したりできます。 
---
= リソースグループの管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
バックアップリソースグループを作成、変更、削除したり、リソースグループに対してバックアップ処理を実行したりできます。


NOTE: Virtual Storage Console（VSC）では、リソースグループはバックアップジョブと呼ばれます。



== リソースグループに対する処理の一時停止と再開

リソース グループでスケジュールされた操作を一時停止します。必要に応じて再度有効にします。

.手順
. SCVプラグインの左側のナビゲーションペインで、*[Resource Groups]*を選択し、リソースグループを選択して*[Suspend]*を選択します（または*[Resume]*を選択します）。
. 確認ボックスで* OK *を選択して確定します。


.終了後
[Resource Groups]ページで、一時停止したリソースのジョブステータスはです `Under_Maintenance`。[Job Status]列が表示されるまで、表を右にスクロールしなければならない場合があります。

バックアップ処理が再開されると、[Job Status]がに変わります `Production`。



== リソースグループの変更

vCenterでリソースグループ内のリソースの削除や追加、ポリシーの適用解除や適用、スケジュールの変更、その他のリソースグループオプションの変更を行うことができます。

.タスクの内容
リソースグループの名前を変更する場合は、VM、データストア、ポリシー、バックアップ、またはリソースグループの名前に次の特殊文字を使用しないでください。

% & * $ # @ ! \ / ： * ？" < > - | ; ' 、およびスペース。アンダースコア文字 (_) も使用できます。

.手順
. SCVプラグインの左側のナビゲーションペインで、*[Resource Groups]*を選択し、リソースグループを選択して*[Edit]*を選択します。
. [リソースグループの編集]*ウィザードの左側のリストで、変更するカテゴリを選択し、変更内容を入力します。
+
複数のカテゴリに変更を加えることができます。このオプションでは、保護されたセカンダリリソースを編集することもできます。

. [概要]ページが表示されるまで[次へ]*を選択し、*[完了]*を選択します。




== リソースグループの削除

リソースを保護する必要がない場合は、vCenter でリソース グループを削除します。  SnapCenter Plug-in for VMware vSphereを削除する前に、すべてのリソース グループを削除します。

.タスクの内容
リソース グループの削除処理は、すべて強制削除として実行されます。リソース グループを削除すると、システムによって vCenter リソース グループからすべてのポリシーがデタッチされ、 SnapCenter Plug-in for VMware vSphereからリソース グループが削除され、リソース グループのすべてのバックアップとスナップショットが削除されます。


NOTE: SnapVault関係では、最後のスナップショットを削除できないため、リソース グループを削除できません。  SnapVault関係内のリソース グループを削除する前に、System Manager またはONTAP CLI を使用して関係を削除し、最後のスナップショットを削除します。

.手順
. SCVプラグインの左側のナビゲーションペインで、*[Resource Groups]*を選択し、リソースグループを選択して*[Delete]*を選択します。
. *リソース グループの削除* 確認ダイアログで、*OK* を選択して確認します。リソース グループを削除しても、セカンダリ保護は削除されません。必要に応じて、System Manager を使用して二次保護を削除します。リソース グループ用に作成されたコンシステンシ グループは自動的には削除されません。System Manager またはサポートされている別のインターフェイスを使用して、 ONTAPから手動で削除する必要があります。

