---
sidebar: sidebar 
permalink: scpivs44_unmount_a_backup.html 
keywords:  
summary: データストア内のファイルにアクセスする必要がなくなった場合は、バックアップをアンマウントできます。 
---
= バックアップのアンマウント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
データストア内のファイルにアクセスする必要がなくなった場合は、バックアップをアンマウントできます。

VMware vSphereクライアントのユーザーインターフェースにバックアップがマウント済みとして表示されているが、バックアップのアンマウント画面に表示されない場合は、REST APIを使用する必要があります。 `/backup/{backup-Id}/cleanup`範囲外のデータストアをクリーンアップしてから、マウント解除手順を再度試してください。

負荷共有ミラー関係にあるルートボリュームを持つストレージVM（SVM）にNFSデータストアのバックアップコピーをマウントしようとすると、次のエラーが発生する可能性があります。 `You might have reached the maximum number of NFS volumes configured in the vCenter. Check the vSphere Client for any error messages.`この問題を回避するには、*ESX* > *管理* > *設定* > *詳細システム設定* に移動して NFS.MaxVolumes 値を変更し、最大ボリューム設定を変更します。最大値は256です。

.手順
. VMware vSphere Clientのショートカットページで、*[ストレージ]*を選択します。
. 左側のナビゲーションペインで、データストアを右クリックし、ドロップダウンリストから* SnapCenter Plug-in for VMware vSphere *を選択し、2番目のドロップダウンリストから*アンマウント*を選択します。
+

IMPORTANT: アンマウントするデータストアを間違えないようにしてください。そうしないと、本番環境の作業に影響を与える可能性があります。

. [Unmount Cloned Datastore]ダイアログボックスで、データストアを選択し、*[Unmount the cloned datastore]*チェックボックスを選択して*[Unmount]*を選択します。

