---
sidebar: sidebar 
permalink: scpivs44_download_the_ova_open_virtual_appliance.html 
keywords:  
summary: .tarファイルには、VMとデータストアのデータ保護用の一連のマイクロサービスであるOVAと、証明書ファイルが含まれています。 
---
= Open Virtual Appliance（OVA；オープン仮想アプライアンス）のダウンロード
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Open Virtual Appliance（OVA；オープン仮想アプライアンス）をインストールする前に、vCenterに証明書を追加してください。.tarファイルにはOVA証明書とEntrust Root証明書とIntermediate証明書が含まれており、証明書は証明書フォルダ内にあります。OVA環境はVMware vCenter 7u1以降でサポートされます。

VMware vCenter 7.0.3以降のバージョンでは、Entrust証明書によって署名されたOVAは信頼されなくなりました。問題 を解決するには、次の手順 を実行する必要があります。

.手順
. SnapCenter Plug-in for VMwareをダウンロードするには、次の手順を実行します。
+
** ネットアップサポートサイト（ https://mysupport.netapp.com/products/index.html["https://mysupport.netapp.com/products/index.html"^]）。
** 製品のリストから、「 SnapCenter Plug-in for VMware vSphere * 」を選択し、「最新リリースをダウンロード」ボタンをクリックします。
** SnapCenter Plug-in for VMware vSphereをダウンロードします `.tar` 任意の場所にファイルを移動します。


. tarファイルの内容を展開します。tarファイルには、ovaフォルダとcertsフォルダが含まれています。certsフォルダには、Entrustルート証明書と中間証明書が含まれています。
. vSphere ClientからvCenter Serverにログインします。
. [管理]>[証明書]>[証明書の管理]に移動します。
. [信頼されたルート証明書]*の横にある*[追加]*をクリックします
+
** _certs_folderに移動します。
** Entrustルート証明書と中間証明書を選択します。
** 各証明書を一度に1つずつインストールします。


. 証明書は*信頼されたルート証明書*の下のパネルに追加されます。証明書をインストールすると、OVAを検証して導入できます。



NOTE: ダウンロードしたOVAが改ざんされていない場合は、「* Publisher *」列に「* Trusted certificate *」と表示されます。
