---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_overview.html 
keywords:  
summary: Windows ゲスト OS の仮想マシンディスク（ VMDK ）からファイルやフォルダをリストアすることができます。 
---
= ワークフロー、前提条件、および制限事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Windows ゲスト OS の仮想マシンディスク（ VMDK ）からファイルやフォルダをリストアすることができます。



== ゲストのリストアワークフロー

ゲスト OS のリストア処理は、次の手順で行います。

. 添付（ Attach ）
+
仮想ディスクをゲスト VM またはプロキシ VM に接続し、ゲストファイルのリストアセッションを開始します。

. お待ちください
+
接続処理が完了するまで待ってから、参照とリストアを実行できます。が接続されたとき

+
処理が完了すると、ゲストファイルのリストアセッションが自動的に作成され、 E メール通知が送信されます

+
送信しました。

. ファイルまたはフォルダを選択します
+
ゲストファイルリストアセッションで VMDK を参照し、リストアするファイルまたはフォルダを 1 つ以上選択します。

. リストア
+
選択したファイルまたはフォルダを指定した場所にリストアします。





== ゲストファイルおよびフォルダをリストアするための前提条件

Windows ゲスト OS 上の VMDK から 1 つ以上のファイルやフォルダをリストアする前に、それらの要件をすべて把握しておく必要があります。

* VMware Tools がインストールされ、実行されている必要があります。
+
SnapCenter は、 VMware Tools の情報を使用して、 VMware ゲスト OS への接続を確立します。

* Windows ゲスト OS で Windows Server 2008 R2 以降が実行されている必要があります。
+
サポートされているバージョンの最新情報については、を参照してください https://imt.netapp.com/matrix/imt.jsp?components=103284;&solution=1517&isHWU&src=IMT["ネットアップの Interoperability Matrix Tool （ IMT ）"^]。

* ターゲット VM のクレデンシャルで、組み込みのドメイン管理者アカウントまたは組み込みのローカル管理者アカウントを指定する必要があります。ユーザ名は「 Administrator 」である必要があります。 リストア処理を開始する前に、仮想ディスクを接続する VM のクレデンシャルを設定する必要があります。このクレデンシャルは、接続処理と後続のリストア処理の両方で必要になります。ワークグループユーザは、組み込みのローカル管理者アカウントを使用できます。
+

IMPORTANT: ビルトインの管理者アカウントではなく、 VM 内で管理者権限を持つアカウントを使用する必要がある場合は、ゲスト VM で UAC を無効にする必要があります。

* リストア元のバックアップ Snapshot コピーと VMDK を確認しておく必要があります。
+
SnapCenter Plug-in for VMware vSphere では、リストアするファイルやフォルダの検索がサポートされません。そのため、作成を開始する前に、 Snapshot コピーと対応する VMDK に関するファイルやフォルダの場所を確認しておく必要があります。

* 接続する仮想ディスクは SnapCenter バックアップに含まれている必要があります。
+
リストアするファイルまたはフォルダが格納されている仮想ディスクが、 SnapCenter Plug-in for VMware vSphere 仮想アプライアンスを使用して実行された VM バックアップに含まれている必要があります。

* プロキシ VM を使用するには、プロキシ VM が設定されている必要があります。
+
仮想ディスクをプロキシ VM に接続する場合は、接続とリストア処理を開始する前にプロキシ VM を設定する必要があります。

* アルファベット以外の名前のファイルの場合、単一のファイルではなくディレクトリにリストアする必要があります。
+
日本語の漢字などのアルファベット以外の名前でファイルを復元するには、ファイルがあるディレクトリを復元します。

* Linux ゲスト OS からのリストアはサポートされていません
+
Linux ゲスト OS を実行している VM からはファイルやフォルダをリストアできません。ただし、 VMDK を接続し、ファイルとフォルダを手動でリストアすることは可能です。サポートされているゲスト OS の最新情報については、を参照してください https://imt.netapp.com/matrix/imt.jsp?components=103284;&solution=1517&isHWU&src=IMT["ネットアップの Interoperability Matrix Tool （ IMT ）"^]。





== ゲストファイルのリストアに関する制限事項

ゲスト OS からファイルまたはフォルダをリストアする前に、この機能がサポートしていない機能について確認しておく必要があります。

* ゲスト OS 内で動的ディスクタイプをリストアすることはできません。
* 暗号化されたファイルまたはフォルダをリストアしても、暗号化属性は保持されません。暗号化されたフォルダにファイルやフォルダをリストアすることはできません。
* [ ゲストファイルの参照 ] ページには、フィルタできない隠しファイルと隠しフォルダが表示されます。
* Linux ゲスト OS からはリストアできません。
+
Linux ゲスト OS を実行している VM からはファイルやフォルダをリストアできません。ただし、 VMDK を接続し、ファイルとフォルダを手動でリストアすることは可能です。サポートされているゲスト OS の最新情報については、を参照してください https://imt.netapp.com/matrix/imt.jsp?components=103284;&solution=1517&isHWU&src=IMT["ネットアップの Interoperability Matrix Tool （ IMT ）"^]。

* NTFS ファイルシステムから FAT ファイルシステムにリストアすることはできません。
+
NTFS 形式から FAT 形式にリストアしようとしても、 NTFS セキュリティ記述子はコピーされません。 FAT ファイルシステムでは Windows セキュリティ属性がサポートされないためです。

* クローン VMDK または初期化されていない VMDK からゲストファイルをリストアすることはできません。
* ONTAP 9.2 以降を実行しているシステムでバックアップが実行されていて、かつ VMware 整合性オプションが有効になっている場合は、セカンダリバックアップからリストアできません。
* ファイルのディレクトリ構造をリストアすることはできません。
+
ネストされたディレクトリ内のファイルをリストア対象として選択した場合、そのファイルは同じディレクトリ構造でリストアされません。ディレクトリツリーはリストアされず、ファイルだけがリストアされます。ディレクトリツリーをリストアする場合は、ディレクトリ自体を構造の最上部にコピーできます。

* VVol VM からゲストファイルをリストアすることはできません。
* 暗号化されたゲストファイルはリストアできません。

