---
sidebar: sidebar 
permalink: scpivs44_disable_and_enable_plugin.html 
keywords:  
summary: SnapCenterのデータ保護機能が不要になった場合は、SnapCenter Plug-in for VMware vSphereの設定を変更する必要があります。たとえば、テスト環境にプラグインを導入した場合は、その環境で SnapCenter 機能を無効にして、本番環境で有効にする必要があります。 
---
= SnapCenter Plug-in for VMware vSphereを無効にして有効にする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenterのデータ保護機能が不要になった場合は、SnapCenter Plug-in for VMware vSphereの設定を変更する必要があります。たとえば、テスト環境にプラグインを導入した場合は、その環境で SnapCenter 機能を無効にして、本番環境で有効にする必要があります。

.開始する前に
* 管理者権限が必要です。
* 実行中のSnapCenterジョブがないことを確認します。


.タスクの内容
SnapCenter Plug-in for VMware vSphereを無効にすると、すべてのリソースグループが中断され、プラグインがvCenterで拡張機能として登録解除されます。

SnapCenter Plug-in for VMware vSphereを有効にすると、プラグインがvCenterで拡張機能として登録され、すべてのリソースグループが本番モードになり、すべてのスケジュールが有効になります。

.手順
. オプション：新しい仮想アプライアンスにリストアする場合に備えて、SnapCenter Plug-in for VMware vSphere MySQLリポジトリをバックアップします。
+
link:scpivs44_back_up_the_snapcenter_plug-in_for_vmware_vsphere_mysql_database.html["SnapCenter Plug-in for VMware vSphere MySQLデータベースのバックアップ"]です。

. 次の形式を使用して、SnapCenter Plug-in for VMware vSphere管理ユーザーインターフェイスにログインします。 `\https://<OVA-IP-address>:8080` 。導入時に設定した管理者ユーザ名とパスワード、およびメンテナンス コンソールを使用して生成されたMFAトークンを使用してログインします。
+
プラグインの導入時に、SnapCenter Plug-in for VMware vSphereのIPアドレスが表示されます。

. 左側のナビゲーションペインで*[設定]*を選択し、*[プラグインの詳細]*セクションで[サービス]オプションの選択を解除してプラグインを無効にします。
. 選択内容を確認します。
+
** VMと整合性のあるバックアップを実行するためにSnapCenter Plug-in for VMware vSphereのみを使用した場合
+
プラグインは無効になっており、これ以上の操作は必要ありません。

** SnapCenter Plug-in for VMware vSphereを使用してアプリケーションと整合性のあるバックアップを実行した場合
+
プラグインが無効になっているため、さらにクリーンアップが必要です。

+
... VMware vSphereにログインします。
... VMの電源をオフにします。
... 左側のナビゲーション画面で、SnapCenter Plug-in for VMware vSphereのインスタンス（仮想アプライアンスの導入時に使用されたファイルの名前）を右クリックし `.ova` 、*[ディスクから削除]*を選択します。
... SnapCenterにログインし、vSphereホストを削除します。





