---
sidebar: sidebar 
permalink: scpivs44_unmount_a_backup.html 
keywords:  
summary: データストア内のファイルにアクセスする必要がなくなった場合は、バックアップをアンマウントできます。 
---
= バックアップをアンマウント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
データストア内のファイルにアクセスする必要がなくなった場合は、バックアップをアンマウントできます。

バックアップが VMware vSphere Web Client GUI にマウント済みとして表示されているが、アンマウントバックアップ画面に表示されていない場合は、 REST API の「 /backup/{backup-ID}/cleanup 」を使用してバインド解除されたデータストアをクリーンアップし、アンマウント手順を再試行する必要があります。

負荷共有ミラー関係が確立されたルートボリュームを含む Storage VM （ SVM ）に NFS データストアのバックアップコピーをマウントしようとすると、「 You may have reached the maximum number of NFS volumes configured in the vCenter 」というエラーが表示されることがあります。vSphere Client でエラーメッセージを確認してください この問題を回避するには、 [*ESX*>*Manage*>*Settings*>*Advance System Settings*] に移動して NFS.MaxVolumes の値を変更し、最大ボリューム数の設定を変更します。最大値は 256 です。

.手順
. VMware vSphere Web Client で、ツールバーの * メニュー * をクリックし、ドロップダウンリストから * ストレージ * を選択します。
. 左側のナビゲーションペインで、データストアを右クリックし、ドロップダウンリストから「 * NetApp SnapCenter * 」を選択してから、セカンダリドロップダウンリストから「 Unmount 」を選択します。
+

IMPORTANT: アンマウントするデータストアを間違えないようにしてください。そうしないと、原因が本番環境に与える影響が発生する可能性があります。

. Unmount cloned Datastore * ダイアログボックスで、データストアを選択し、 * Unmount the cloned datastore * チェックボックスをオンにして、 * Unmount * をクリックします。

