---
sidebar: sidebar 
permalink: scpivs44_view_status_information.html 
keywords:  
summary: vSphere Client Dashboardにはステータス情報が表示されます。ステータス情報は 1 時間に 1 回更新されます。 
---
= ステータス情報を表示します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vSphere Client Dashboardにはステータス情報が表示されます。ステータス情報は 1 時間に 1 回更新されます。

.手順
. vSphereクライアントの左側のナビゲーションペインで、*ダッシュボード*をクリックし、vCenter Serverを選択して、ダッシュボードペインの*ステータス*タブをクリックします。
. 次の表に示すように、概要のステータス情報を表示するか、リンクをクリックして詳細を確認します。
+
|===
| このダッシュボードタイル… | 次の情報を表示します。 


 a| 
最近のジョブアクティビティ
 a| 
最新のバックアップ、リストア、およびマウントジョブが 3~5 つ実行されています。

** ジョブ ID をクリックすると、そのジョブの詳細が表示されます。
** すべてのジョブの詳細については、 [ すべて表示 ] をクリックして [ ジョブモニタ ] タブに移動します。




 a| 
ジョブ
 a| 
選択した期間内に実行された各ジョブタイプ（バックアップ、リストア、マウント）の数。グラフのセクションにカーソルを合わせると、そのカテゴリの詳細が表示されます。



 a| 
最新の保護の概要
 a| 
選択した期間内のプライマリ VM およびセカンダリ VM またはデータストアのデータ保護ステータスの概要。

** ドロップダウンメニューをクリックして、 * VMS * または * Datastores * を選択します。
** セカンダリストレージの場合は、 * SnapVault * または * SnapMirror * を選択します。
** グラフのセクションにカーソルを合わせると、そのカテゴリの VM またはデータストアの数が表示されます。Successful カテゴリには、各リソースの最新のバックアップが表示されます。
** 設定ファイルを編集することによって、時間ウィンドウを変更できます。デフォルトは 7 日です。詳細については、を参照してください link:scpivs44_customize_your_configuration.html["設定をカスタマイズします"]。
** 内部カウンタは、プライマリまたはセカンダリのバックアップが完了するたびに更新されます。ダッシュボードのタイルは 6 時間ごとに更新されます。更新時間は変更できません。注：ミラーバックアップ保護ポリシーを使用している場合は、保護の概要のカウンタが SnapMirror チャートではなく SnapVault の概要チャートに表示されます。




 a| 
設定
 a| 
SnapCenter Plug-in for VMware vSphere で管理されている各タイプのオブジェクトの総数。



 a| 
ストレージ
 a| 
Snapshot、SnapVault、SnapMirror Snapshotの総数と、生成されたプライマリSnapshotとセカンダリSnapshotに使用されているストレージ容量。このグラフには、連続した 90 日間におけるプライマリとセカンダリのストレージ消費量が 1 日単位で表示されます。ストレージ情報は、24時間ごとに午前1時8分に1回更新されます
ストレージ削減率は、プライマリストレージの物理容量に対する論理容量（Snapshotによる削減量とストレージ消費量の合計）の比率です。棒グラフは、ストレージの削減量を示します。

グラフ上の線にカーソルを合わせると、詳細な 1 日ごとの結果が表示されます。

|===

