---
sidebar: sidebar 
permalink: scpivs44_restore_deleted_vms_from_backups.html 
keywords:  
summary: 削除したVMは、データストアのプライマリバックアップまたはセカンダリバックアップから選択したESXiホストにリストアできます。 
---
= 削除したVMをバックアップからリストア
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
削除したVMは、データストアのプライマリバックアップまたはセカンダリバックアップから選択したESXiホストにリストアできます。

VMは次の場所にリストアできます。

* 元の場所にリストア
+
** 元のESXiホストにマウントされている元のデータストア（VMのコピーが作成されます）


* 別の場所へのリストア
+
** 元のESXiホストにマウントされている別のデータストア
** 同じvCenterで管理されている別のESXiホストにマウントされている元のデータストア
** 同じvCenterで管理されている別のESXiホストにマウントされている別のデータストア
** リンクモードの別のvCenterで管理されている別のESXiホストにマウントされている別のデータストア





NOTE: 別の場所にリストアする場合は、リストア処理のデスティネーションであるリンクされたvCenterでSnapCenter Plug-in for VMware vSphereが実行されている必要があります。デスティネーションデータストアに十分なスペースが必要です。


NOTE: VVOL VMを別の場所にリストアすることはできません。


NOTE: 削除されたVMをリストアする場合、そのVMに最初に割り当てられていたタグやフォルダはリストアされません。

.開始する前に
* VMware vSphere Clientの[Storage Systems]ページにあるストレージシステムのユーザアカウントには、が必要です link:scpivs44_minimum_ontap_privileges_required.html["ONTAP に必要な最小限の ONTAP 権限"]。
* vCenterのユーザアカウントにが必要です link:scpivs44_minimum_vcenter_privileges_required.html["SnapCenter Plug-in for VMware vSphere に必要な最小限の vCenter 権限"]。
* バックアップが存在している必要があります。
+
SnapCenter Plug-in for VMware vSphereを使用してVMのバックアップを作成してから、そのVMにVMDKをリストアしておく必要があります。




TIP: NFS環境でのリストア処理のパフォーマンスを向上させるには、VMwareアプリケーションのvStorage API for Array Integration（VAAI）を有効にします。

.タスクの内容
データストアはリストアできませんが、データストア内のVMはリストアできます。

VMが配置されているFabricPoolのストレージ階層を使用できない場合、リストア処理が失敗することがあります。

.手順
. [ * メニュー * ] をクリックし、 [ * ストレージ * ] メニュー・オプションを選択してから、データストアを選択し、 [ * 構成 * ] タブを選択して、 [ * SnapCenter Plug-in for VMware vSphere * ] セクションの [ * バックアップ * ] をクリックします。
. バックアップをダブルクリックすると、バックアップに含まれるすべてのVMのリストが表示されます。
. バックアップ・リストから削除された VM を選択し、 * リストア * をクリックします。
. リストア * ウィザードの * バックアップの選択 * ページで、リストア元のバックアップ・コピーを選択します。
+
特定のバックアップ名またはバックアップ名の一部を検索するか、バックアップリストをフィルタすることができます。フィルタアイコンをクリックし、日時の範囲、VMwareスナップショットを含むバックアップの有無、マウントするバックアップの有無、および場所を選択します。[OK] をクリックしてウィザードに戻ります。

. [Select Scope]ページで、[Restore scope]フィールドで*[Entire virtual machine]*を選択し、リストア先を選択してから、バックアップをマウントするデスティネーションESXiホストの情報を入力します。
+
リストア先は、SnapCenterに追加されている任意のESXiホストにすることができます。このオプションを選択すると、指定した日時のスナップショットから、VMが存在していた選択したバックアップの内容がリストアされます。このオプションを選択して VM の電源をオンにすると、 * Restart VM * チェックボックスがオンになります。

+
NFSデータストア内のVMをESXiクラスタ内の代替ESXiホストにリストアすると、リストア後にそのVMが代替ホストに登録されます。

. ［ * 場所の選択 * ］ ページで、リストア元のバックアップ（プライマリまたはセカンダリ）の場所を選択します。
. [ 概要 ] ページを確認し、 [ 完了 ] をクリックします。

