---
sidebar: sidebar 
permalink: scpivs44_how_restore_operations_are_performed.html 
keywords:  
summary: VMFS 環境の場合、 SnapCenter Plug-in for VMware vSphere は、リストア処理を実行するために、 Storage VMotion でクローンおよびマウント処理を使用します。NFS 環境の場合、このプラグインはネイティブの ONTAP Single File SnapRestore （ SFSR ）を使用して、ほとんどのリストア処理を効率よく実行できます。 
---
= リストア処理の実行方法
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


VMFS 環境の場合、 SnapCenter Plug-in for VMware vSphere は、リストア処理を実行するために、 Storage VMotion でクローンおよびマウント処理を使用します。NFS 環境の場合、このプラグインはネイティブの ONTAP Single File SnapRestore （ SFSR ）を使用して、ほとんどのリストア処理を効率よく実行できます。次の表に、リストア処理の実行方法を示します。

|===
| リストア処理 | NFS 環境での ONTAP SFSR を使用して実行します | NFS 環境で Storage VMotion を使用してクローンとマウントを実行 | VMFS 環境で Storage VMotion を使用してクローンとマウントを実行 


| プライマリバックアップからの VM および VMDK のリストア | はい。 |  | はい。 


| セカンダリバックアップからの VM および VMDK のリストア | はい。 |  | はい。 


| 削除された VM と VMDK をプライマリバックアップからリストアする | はい。 |  | はい。 


| セカンダリバックアップから削除された VM と VMDK をリストアする |  | はい。 | はい。 


| VM と整合性のあるプライマリバックアップからの VM と VMDK のリストア | はい。 |  | はい。 


| VM と整合性のあるセカンダリバックアップからの VM と VMDK のリストア |  | はい。 | はい。 
|===
ゲストファイルのリストア操作は、 NFS 環境と VMFS 環境の両方で、（ Storage VMotion ではなく）クローン操作とマウント操作を使用して実行されます。


IMPORTANT: リストア処理中に、「 Host unresolved volumes is null' or ’ Exception while calling pre-restore on SCV … . Error mounting cloned LUN as datastore.` 」というエラーが発生することがあります これは、 SnapCenter VMware プラグインがクローンの再署名を試みたときに発生します。VMware の制限により、 SnapCenter VMware プラグインは高度な ESXi 構成で自動再署名値を制御できません。

このエラーの詳細については、 ｛ linkwith -forアンダー スコア ｝ [ 技術情報： SCV clone or restores fail with error 'Host Unresolved volumes is null^] を参照してください。
