---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_overview.html 
keywords:  
summary: WindowsゲストOSの仮想マシンディスク（VMDK）からファイルやフォルダをリストアできます。 
---
= ワークフロー、前提条件、および制限事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
WindowsゲストOSの仮想マシンディスク（VMDK）からファイルやフォルダをリストアできます。



== ゲストリストアのワークフロー

ゲストOSのリストア処理には、次の手順が含まれます。

. 添付
+
仮想ディスクをゲストVMまたはプロキシVMに接続し、ゲストファイルのリストアセッションを開始します。

. 待機
+
接続処理が完了するまで、参照およびリストアを実行できません。取り付け時

+
処理が完了すると、ゲストファイルのリストアセッションが自動的に作成され、Eメール通知が

+
送信済み。

. ファイルまたはフォルダの選択
+
[Guest File Restore]セッションでVMDKを参照し、リストアするファイルまたはフォルダを1つ以上選択します。

. リストア
+
選択したファイルまたはフォルダを指定した場所にリストアします。





== ゲストファイルおよびフォルダをリストアするための前提条件

WindowsゲストOSでVMDKから1つ以上のファイルまたはフォルダをリストアする前に、すべての要件を確認しておく必要があります。

* VMware Toolsがインストールされ、実行されている必要があります。
+
SnapCenterは、VMwareツールからの情報を使用して、VMwareゲストOSへの接続を確立します。

* WindowsゲストOSでWindows Server 2008 R2以降が実行されている必要があります。
+
サポートされているバージョンの最新情報については、を参照してください https://imt.netapp.com/matrix/imt.jsp?components=121034;&solution=1517&isHWU&src=IMT["NetApp Interoperability Matrix Tool（IMT）"^]。

* ターゲットVMのクレデンシャルで、ビルトインドメイン管理者アカウントまたはビルトインローカル管理者アカウントを指定する必要があります。ユーザ名は「Administrator」である必要があります。リストア処理を開始する前に、仮想ディスクを接続するVMのクレデンシャルを設定する必要があります。このクレデンシャルは、接続処理と後続のリストア処理の両方で必要です。ワークグループユーザは、組み込みのローカル管理者アカウントを使用できます。
+

IMPORTANT: 組み込みの管理者アカウントではなく、VM内の管理者権限を持つアカウントを使用する必要がある場合は、ゲストVMのUACを無効にする必要があります。

* リストア元のバックアップSnapshotとVMDKを確認しておく必要があります。
+
SnapCenter Plug-in for VMware vSphereでは、リストアするファイルやフォルダの検索はサポートされていません。そのため、作業を開始する前に、Snapshotと対応するVMDKに対するファイルまたはフォルダの場所を把握しておく必要があります。

* 接続する仮想ディスクはSnapCenterバックアップに含まれている必要があります。
+
リストアするファイルまたはフォルダが格納されている仮想ディスクが、SnapCenter Plug-in for VMware vSphere仮想アプライアンスを使用して実行されたVMバックアップに含まれている必要があります。

* プロキシVMを使用するには、プロキシVMを設定する必要があります。
+
仮想ディスクをプロキシVMに接続する場合は、接続およびリストア処理を開始する前にプロキシVMを設定する必要があります。

* 英語以外のアルファベット名のファイルの場合は、単一のファイルとしてではなく、ディレクトリにリストアする必要があります。
+
日本語の漢字など、アルファベット以外の名前のファイルをリストアするには、ファイルが配置されているディレクトリをリストアします。

* LinuxゲストOSからのリストアはサポートされない
+
LinuxゲストOSを実行しているVMからファイルやフォルダをリストアすることはできません。ただし、VMDKを接続し、ファイルとフォルダを手動でリストアすることもできます。サポートされているゲストOSの最新情報については、を参照してください https://imt.netapp.com/matrix/imt.jsp?components=121034;&solution=1517&isHWU&src=IMT["NetApp Interoperability Matrix Tool（IMT）"^]。





== ゲストファイルのリストアの制限事項

ゲストOSからファイルまたはフォルダをリストアする前に、この機能でサポートされない機能について理解しておく必要があります。

* ゲストOS内でダイナミックディスクタイプをリストアすることはできません。
* 暗号化されたファイルまたはフォルダを復元した場合、暗号化属性は保持されません。ファイルまたはフォルダを暗号化されたフォルダにリストアすることはできません。
* [Guest File Browse]ページには、非表示のファイルとフォルダが表示されますが、フィルタリングすることはできません。
* LinuxゲストOSからはリストアできません。
+
LinuxゲストOSを実行しているVMからファイルやフォルダをリストアすることはできません。ただし、VMDKを接続し、ファイルとフォルダを手動でリストアすることもできます。サポートされているゲストOSの最新情報については、を参照して https://imt.netapp.com/matrix/imt.jsp?components=121034;&solution=1517&isHWU&src=IMT["NetApp Interoperability Matrix Tool（IMT）"^]ください。

* NTFSファイルシステムからFATファイルシステムにリストアすることはできません。
+
NTFS形式からFAT形式にリストアしようとすると、FATファイルシステムはWindowsセキュリティ属性をサポートしていないため、NTFSセキュリティ記述子はコピーされません。

* クローニングされたVMDKまたは初期化されていないVMDKからゲストファイルをリストアすることはできません。
* ONTAP 9 .2以降を実行しているシステムでバックアップを実行し、VMware整合性オプションがonの場合は、セカンダリバックアップからリストアすることはできません。
* ファイルのディレクトリ構造はリストアできません。
+
ネストされたディレクトリ内のファイルをリストア対象として選択した場合、そのファイルは同じディレクトリ構造ではリストアされません。ディレクトリツリーはリストアされず、ファイルのみがリストアされます。ディレクトリツリーをリストアする場合は、構造体の最上部にディレクトリ自体をコピーできます。

* VVOL VMから別のホストにゲストファイルをリストアすることはできません。
* 暗号化されたゲストファイルはリストアできません。

