---
sidebar: sidebar 
permalink: scpivs44_manage_policies.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere のバックアップポリシーを作成、変更、表示、適用解除、および削除できます。データ保護処理を実行するにはポリシーが必要です。 
---
= ポリシーを管理する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere のバックアップポリシーを作成、変更、表示、適用解除、および削除できます。データ保護処理を実行するにはポリシーが必要です。



== ポリシーを適用解除

リソースのデータ保護を管理するポリシーが不要になった場合は、SnapCenter Plug-in for VMware vSphereリソースグループからポリシーの適用を解除できます。ポリシーを削除する前、またはスケジュール頻度を変更する前に、ポリシーの適用を解除する必要があります。

.このタスクについて
SnapCenter Plug-in for VMware vSphereリソースグループからポリシーの適用を解除するためのガイドラインは、SnapCenterリソースグループのガイドラインとは異なります。VMware vSphere Clientリソースグループの場合は、すべてのポリシーの適用を解除できます。その結果、リソースグループにポリシーがなくなります。ただし、そのリソースグループに対してデータ保護処理を実行するには、少なくとも1つのポリシーを適用する必要があります。

.手順
. SCVプラグインの左側のナビゲーションペインで、*[リソースグループ]*をクリックし、リソースグループを選択して*[編集]*をクリックします。
. リソースグループの編集ウィザードの * ポリシー * ページで、適用解除するポリシーの横にあるチェックマークをオフにします。
+
ポリシーのチェックマークをオンにすると、ポリシーがリソースグループに追加されます。

. ウィザードの残りの部分でリソースグループに追加の変更を加えてから、 [ 完了 ] をクリックします。




== ポリシーを変更する

SnapCenter Plug-in for VMware vSphere リソースグループのポリシーを変更することができます。  リソースグループにポリシーが適用されている場合は、頻度、レプリケーションオプション、Snapshotの保持設定、またはスクリプトの情報を変更できます。

.このタスクについて
SnapCenter Plug-in for VMware vSphereのバックアップポリシーの変更は、SnapCenterアプリケーションベースのプラグインのバックアップポリシーの変更とは異なります。プラグインのポリシーを変更するときに、リソースグループからポリシーの適用を解除する必要はありません。

レプリケーションまたは保持の設定を変更する前に、その影響を考慮する必要があります。

* レプリケーションまたは保持の設定を増やしています
+
新しい設定に達するまでバックアップが蓄積され続けます。

* レプリケーションまたは保持の設定を引き下げる場合
+
新しい設定を超過したバックアップは、次のバックアップの実行時に削除されます。




NOTE: SnapCenter Plug-in for VMware vSphereポリシーのスケジュールを変更するには、プラグインリソースグループでスケジュールを変更する必要があります。

.手順
. SCVプラグインの左側のナビゲータペインで、*[Policies]*をクリックし、ポリシーを選択して*[Edit]*をクリックします。
. ポリシーのフィールドを変更します。
. 完了したら、 * アップデート * をクリックします。


変更は、スケジュールされたバックアップが次回実行されるときに有効になります。



== ポリシーを削除する

SnapCenter Plug-in for VMware vSphere 用に設定したバックアップポリシーが不要になった場合は、必要に応じて削除することができます。

.作業を開始する前に
SnapCenter の仮想アプライアンスを削除する前に、そのポリシーをすべてのリソースグループから解除しておく必要があります。

.手順
. SCVプラグインの左側のナビゲータペインで、*[Policies]*をクリックし、ポリシーを選択して*[Remove]*をクリックします。
. 確認ダイアログボックスで、 * OK * をクリックします。

