---
sidebar: sidebar 
permalink: scpivs44_migration_overview.html 
keywords:  
summary:  
---
= データ移行の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
移行コマンドは、 #SnapCenter 4.0 以降の # からメタデータを移行します。以前のバージョンの SnapCenter を使用している場合は、移行前にアップグレードする必要があります。

* 移行の内容には、が含まれ
+
** 移行の内容
+
SnapCenter メタデータ。ストレージシステム、カスタマイズされたスロットル、 SnapCenter 構成ファイルの E メール設定、ポリシー、リソースグループ、バックアップメタデータ、およびマウントが含まれます。（プリスクリプトまたはポストスクリプトが検出されると移行が失敗する）

** 何が移行されないか
+
リソースグループに対して設定された、事前および事後スクリプト

+
アクティブなゲストファイルのリストアセッション、ゲストファイルのリストアクレデンシャル、およびプロキシ VM

+
ゲストファイルの復元セッションがアクティブなときに移行を開始すると、セッションが削除され、接続されたディスクはアンマウントされません。接続されているディスクを手動で削除しなければならない場合があります。

+
'cbr.override' 設定ファイル



* SnapCenter ホストが一時停止されている
+
移行が確実に成功するために、移行コマンドは SnapCenter に登録されているすべてのホストを一時停止します。移行プロセスが正常に完了すると、 SnapCenter ホストが再開されます。

* 移行コマンドレットのプロセス
+
SnapCenterに登録されているSnapCenter Plug-in for VMware vSphereのインスタンスごとに、Windows PowerShellコマンドレットを使用する必要があります `invoke-SCVOVAMigration` 。

+
このコマンドレットでは次の処理が実行されます

+
** 移行中にジョブが失敗しないように、すべてのスケジュールを一時停止します。移行が成功すると、スケジュールは自動的に再度有効になります。
** ストレージ接続とメタデータを移行します。
** 移行後のバックアップのバックアップスケジュールを作成します。
** Windows ホストから既存の SnapCenter Plug-in for VMware vSphere をアンインストールします。
+
SnapCenter Plug-in for VMware vSphereがSnapCenter Serverホストにインストールされていて、SnapCenterリポジトリ用に保護が設定されている場合は、SnapCenter Plug-in for VMware vSphereおよびSnapCenter Plug-in for Windowsを含むWindowsベースのプラグインパッケージも移行プロセスによってアンインストールされます。 その後、リポジトリ保護をサポートするために最新バージョンのSnapCenter Plug-in for Windowsを再インストールします。SnapCenter GUIのホストタイプが「vsphere」から「windows」に変わります。

** Windows SnapCenter サーバから vSphere ホストとリソースグループを削除します。
** LinuxベースのSnapCenter Plug-in for VMware vSphereでバックアップジョブをアクティブ化します。
** SnapCenter Plug-in for VMware vSphereのvSphereホストをSnapCenterに登録して、仮想化されたデータベースとファイルシステムのアプリケーションベースのバックアップ（VMDKバックアップ経由のアプリケーション）をサポートします。


* メタデータの保存場所
+
アプリケーションベースのVMDKバックアップのメタデータは、SnapCenterサーバリポジトリに格納されます。VMとデータストアのバックアップのメタデータは、SnapCenter Plug-in for VMware vSphere MySQLリポジトリに格納されます。


