---
sidebar: sidebar 
permalink: scpivs44_guest_file_restore_scenarios_you_might_encounter.html 
keywords:  
summary: ゲストファイルをリストアしようとすると、ゲストファイルのリストアセッションが空白になったり、ゲストファイルのリストア接続ディスクの処理が失敗したり、ゲストファイルのリストアセッションが終了したあとにバックアップが切断されない場合があります。 
---
= ゲストファイルのリストアシナリオ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ゲストファイルをリストアしようとすると、次のいずれかの状況が発生することがあります。



== ゲストファイルのリストアセッションが空白である

この問題は、ゲストファイルリストアセッションを作成したときに、そのセッションがアクティブであったときにゲストオペレーティングシステムがリブートされたときに発生します。この場合、ゲストOSのVMDKはオフラインのままになることがあります。そのため、ゲストファイルリストアセッションを参照しようとすると、リストは空白になります。

この問題を解決するには、ゲストOSでVMDKを手動でオンラインに戻します。VMDKがオンラインになると、ゲストファイルのリストアセッションに正しい内容が表示されます。



== ゲストファイルのリストアの接続ディスク処理が失敗する

この問題は、ゲストファイルのリストア処理を開始しても、VMware Toolsが実行されていてゲストOSのクレデンシャルが正しいにもかかわらず、ディスクの接続処理が失敗する場合に発生します。この場合、次のエラーが返されます。

`Error while validating guest credentials, failed to access guest system using specified credentials: Verify VMWare tools is running properly on system and account used is Administrator account, Error is SystemError vix error codes = (3016, 0).`

この問題を解決するには、ゲストOSでVMware Tools Windowsサービスを再起動してから、ゲストファイルのリストア処理を再試行します。



== ゲストEメールにファイル名として「??????」が表示される

この問題は、ゲストファイルの復元機能を使用して名前に英語以外の文字が含まれているファイルまたはフォルダを復元し、電子メール通知に「？？？？？？？？」と表示される場合に発生します。 」と入力します。電子メールの添付ファイルには、復元されたファイルとフォルダの名前が正しくリストされています。



== ゲストファイルのリストアセッションを中断したあとにバックアップが切断されない

この問題は、VM整合性バックアップからゲストファイルのリストア処理を実行する場合に発生します。ゲストファイルのリストアセッションがアクティブな間に、同じVMに対して別のVM整合性バックアップが実行されます。ゲストファイルリストアセッションが手動または24時間後に自動的に切断されても、セッションのバックアップは切断されません。

この問題を解決するには、アクティブなゲストファイルリストアセッションから接続されていたVMDKを手動で接続解除します。
