---
sidebar: sidebar 
permalink: scpivs44_create_backup_policies_for_vms_and_datastores.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphereを使用してVMとデータストアをバックアップする前に、バックアップポリシーを作成する必要があります。 
---
= VMとデータストアのバックアップポリシーの作成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphereを使用してVMとデータストアをバックアップする前に、バックアップポリシーを作成する必要があります。

.開始する前に
* 前提条件を確認しておく必要があります。
* セカンダリストレージの関係を設定しておく必要があります。
+
** Snapshotをミラーセカンダリストレージまたはバックアップセカンダリストレージにレプリケートする場合は、関係が設定されている必要があり、SnapCenter管理者がソースとデスティネーションの両方のボリューム用にStorage VMを割り当てておく必要があります。
** NFSまたはVMFSデータストア上のVersion-FlexibleMirror関係でスナップショットをセカンダリストレージに正常に転送するには、SnapMirrorポリシータイプが非同期ミラーであり、「all_source_snapshots」オプションがオンになっていることを確認します。
** セカンダリストレージ（mirror-vault）上のSnapshotの数が上限に達すると、バックアップ処理でバックアップを登録して保持を適用する処理が失敗し、次のエラーが表示されます。 `This snapshot is currently used as a reference snapshot by one or more SnapMirror relationships. Deleting the snapshot can cause future SnapMirror operations to fail.`
+
この問題を解決するには、Snapshotの最大数に達しないようにセカンダリストレージのSnapMirror保持ポリシーを設定します。

+
管理者がユーザーにリソースを割り当てる方法については、以下を参照してください。 https://docs.netapp.com/us-en/snapcenter/get-started/rbac-snapcenter.html["ロールベースアクセス制御の使用に関する SnapCenter 情報"^] 。



* VMと整合性のあるバックアップが必要な場合は、VMware Toolsをインストールして実行しておく必要があります。VMを休止するには、VMware Toolsが必要です。VM整合性バックアップはVVOL VMではサポートされません。
* SnapMirror Active Syncを使用すると、サイト全体に障害が発生してもビジネスサービスの運用を継続できるため、アプリケーションをセカンダリコピーを使用して透過的にフェイルオーバーできます。
+

NOTE: SnapMirrorアクティブ同期はVMFSデータストアでのみサポートされます。

+
SnapMirror Active Sync環境でVMFSデータストアを保護するには、SnapCenter管理者が次の作業を行う必要があります。

+
** テクニカルレポートの説明に従って、クラスタとメディエーターを設定します https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/mediator-install-task.html["SnapMirrorアクティブ同期用のONTAP Mediatorとクラスタの設定"]。
** VMFSデータストアに関連付けられているボリュームを整合性グループに追加し、2つのONTAPストレージシステム間に_AutomatedFailOver_or_AutomatedFailOverDuplex_protectionポリシーを使用してデータ保護関係を作成します。_AutomatedFailOverDuplex_policyは、ONTAP 9.15.1リリース以降でサポートされています。





NOTE: ファンアウト構成では、3番目のサイトでは整合グループはサポートされません。

.タスクの内容
ウィザードの各ページのフィールドのほとんどはわかりやすいもので、説明を必要としません。以下の手順では、説明が必要な一部のフィールドを取り上げます。

.手順
. SCVプラグインの左側のナビゲータペインで、*[Policies]*を選択します。
. [ポリシー]*ページで、*[作成]*を選択してウィザードを開始します。
. [新しいバックアップポリシー]*ページで、ポリシーの名前と説明を入力します。
+
** リンクモード
+
リンクモードでは、各vCenterに個別の仮想アプライアンスがあります。そのため、複数のvCenterで重複した名前を使用できます。ただし、ポリシーはリソースグループと同じvCenterで作成する必要があります。

** サポートされない文字
+
VM 、データストア、クラスタ、ポリシー、バックアップ、 またはリソースグループ名： %&*$#@ ！\ / ： * ？" < > - | ; ' 、およびスペース。

+
アンダースコア（_）を使用できます。



. 頻度の設定を指定します。
+
ポリシーではバックアップの頻度のみを指定します。バックアップの具体的な保護スケジュールは、リソースグループで定義します。そのため、複数のリソースグループで同じポリシーとバックアップ頻度を共有していても、バックアップスケジュールが異なる場合があります。

. スナップショットのロックを有効にするには、*[ロック期間]*チェックボックスを選択します。プライマリおよびセカンダリSnapshotのロック期間は、日/月/年として選択できます。
+

NOTE: ONTAP SnapMirrorポリシーで設定された保持値に関係なく、セカンダリSnapshotコピーは、指定されたセカンダリSnapshotロック期間までは削除されません。

. 保持設定を指定します。
+

IMPORTANT: SnapVaultレプリケーションを有効にする場合は、バックアップの保持数を2以上に設定する必要があります。保持するバックアップの保持数を1に設定すると、保持処理が失敗することがあります。これは、新しいSnapshotがターゲットにレプリケートされるまで、最初のSnapshotがSnapVault関係の参照Snapshotになるためです。

+

NOTE: 最大保持数は1018個です。保持数を使用しているONTAPバージョンでサポートされる値よりも大きい値に設定すると、バックアップは失敗します。これは、複数のデータストアにも当てはまります。



. [ * Replication * ] フィールドで、次の表に示すように、セカンダリ・ストレージへのレプリケーションのタイプを指定します。
+
|===
| このフィールドでは… | 操作 


| バックアップ後にSnapMirrorを更新  a| 
プライマリバックアップボリュームとのSnapMirror関係がある別のボリュームにバックアップセットのミラーコピーを作成する場合は、このオプションを選択します。ミラーバックアップ関係が設定されたボリュームでバックアップをミラーバックアップデスティネーションにコピーする場合は、「バックアップ後に SnapVault を更新」オプションのみを選択する必要があります。


NOTE: このオプションは、SnapCenter Plug-in for VMware vSphere 4.5以降のFlexGroupボリュームのデータストアでサポートされます。


NOTE: SnapMirrorアクティブ同期構成でVMFSデータストアを保護するには、開始する前に_セクションに記載されている前提条件を満たし、*[バックアップ後にSnapMirrorを更新する]*を有効にする必要があります。



| バックアップ後にSnapVaultを更新  a| 
プライマリバックアップボリュームとのSnapVault関係がある別のボリュームでディスクツーディスクバックアップレプリケーションを実行する場合は、このオプションを選択します。


IMPORTANT: ボリュームにmirror-vault関係が設定されている場合、このオプションはmirror-vaultデスティネーションにバックアップをコピーする場合にのみ選択する必要があります。


NOTE: このオプションは、SnapCenter Plug-in for VMware vSphere 4.5以降のFlexGroupボリュームのデータストアでサポートされます。



| Snapshotラベル  a| 
このポリシーで作成されたSnapVault SnapshotおよびSnapMirror Snapshotに追加するオプションのカスタムラベルを入力します。Snapshotラベルは、このポリシーで作成されたSnapshotをセカンダリストレージシステム上の他のSnapshotと区別するのに役立ちます。


NOTE: Snapshotラベルに使用できる最大文字数は31文字です。

|===
. オプション： ［ * 詳細設定 * ］ フィールドで、必要なフィールドを選択します。[Advanced]フィールドの詳細を次の表に示します。
+
|===
| このフィールドでは… | 操作 


| VM整合性  a| 
バックアップジョブの実行時に毎回VMを休止してVMwareスナップショットを作成する場合は、このチェックボックスをオンにします。

このオプションはVVOLではサポートされていません。VVol VMの場合は、crash-consistentバックアップのみが実行されます。


IMPORTANT: VM整合性バックアップを実行するには、VMでVMware Toolsが実行されている必要があります。VMware toolsが実行されていない場合は、代わりにcrash-consistentバックアップが実行されます。


NOTE: [VM consistency]チェックボックスをオンにすると、バックアップ処理に時間がかかり、より多くのストレージスペースが必要になることがあります。このシナリオでは、まずVMを休止してから、VMwareがVM整合性スナップショットを実行し、SnapCenterがバックアップ処理を実行してから、VMの処理を再開します。VMゲストメモリは、VM整合性スナップショットには含まれません。



| 独立型ディスクのデータストアを含める | 一時的なデータを含む独立型ディスクのデータストアをバックアップに含める場合は、このボックスをオンにします。 


| スクリプト  a| 
SnapCenter Plug-in for VMware vSphereでバックアップ処理の前後に実行するプリスクリプトまたはポストスクリプトの完全修飾パスを入力します。たとえば、SNMPトラップの更新、アラートの自動化、ログの送信を行うスクリプトを実行できます。スクリプトパスは、スクリプトの実行時に検証されます。


NOTE: プリスクリプトとポストスクリプトは、仮想アプライアンスVMに配置する必要があります。複数のスクリプトを入力するには、スクリプトパスの入力後に * Enter キーを押し、スクリプトごとに改行します。文字は使用できません。

|===
. [追加]を選択します。*
+
ポリシーが作成されたことを確認し、ポリシーページでポリシーを選択してポリシーの設定を確認できます。


