---
sidebar: sidebar 
permalink: scpivs48_rest_apis_audit_logs.html 
keywords:  
summary: 監査ログを生成するREST API 
---
= 監査ログを生成するREST API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
監査ログの詳細は、swagger REST APIおよびSCVプラグインのユーザインターフェイスから収集できます。

次に、Swagger REST APIを示します。

. GET 4.1/audit/logs：すべてのログの監査データを取得します
. GET 4.1/audit/logs/｛fileName｝：特定のログファイルの監査データを取得します
. 4.1/audit/Verify後：監査ログの検証をトリガーします。
. GET 4.1/audit/config：監査およびsyslogサーバの設定を取得します
. PUT 4.1/audit/config：監査サーバとsyslogサーバの設定を更新します


SnapCenter Plug-in for VMware vSphere REST APIを使用してVMware vSphere Clientジョブの監査ログを生成するには、VMware vSphereのREST API呼び出しを使用する必要があります。

各REST APIについて、REST APIの先頭にを追加し `\https://<server>:<port>/api` て完全なエンドポイントを形成します。

ジョブの詳細情報を取得するには、[Jobs]セクションで次のREST APIを使用します。

|===
| REST API | コメント 


| `4.1/audit/logs` | 整合性データを含む監査ログファイルを返します。 


| `4.1/audit/logs/{filename}` | 整合性データを含む特定の監査ログファイルを取得する 


| `4.1/audit/verify` | カンサケンシヨウノトリガー 


| `4.1/audit/syslogcert` | syslogサーバ証明書を更新します 
|===