---
sidebar: sidebar 
permalink: scpivs44_set_up_proxy_vms_for_restore_operations.html 
keywords:  
summary: ゲストファイルのリストア処理にプロキシVMを使用して仮想ディスクを接続する場合は、リストア処理を開始する前にプロキシVMを設定する必要があります。プロキシVMはいつでもセットアップできますが、プラグインの導入が完了したらすぐにセットアップする方が便利な場合があります。 
---
= リストア処理用のプロキシVMのセットアップ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ゲストファイルのリストア処理にプロキシVMを使用して仮想ディスクを接続する場合は、リストア処理を開始する前にプロキシVMを設定する必要があります。プロキシVMはいつでもセットアップできますが、プラグインの導入が完了したらすぐにセットアップする方が便利な場合があります。

.手順
. vSphere Clientのショートカットウィンドウで、[プラグイン]の*[ SnapCenter Plug-in for VMware vSphere ]*を選択します。
. 左側のナビゲーションで、*[ゲストファイルのリストア]*を選択します。
. Run As Credentials * セクションで、次のいずれかを実行します。
+
|===
| これを行うには ... | 操作 


| 既存のクレデンシャルを使用する | 設定されているクレデンシャルを選択します。 


| 新しいクレデンシャルを追加する  a| 
.. 「 * 追加」を選択します。
.. Run As Credentials * ダイアログボックスで、クレデンシャルを入力します。
.. [Select VM]*を選択し、*[Proxy VM]*ダイアログボックスでVMを選択します。[保存]*を選択して*[クレデンシャルとして実行]*ダイアログボックスに戻ります。
.. クレデンシャルを入力します。[Username]に「Administrator」と入力する必要があります。


|===
+
SnapCenter Plug-in for VMware vSphereは、選択したクレデンシャルを使用して、選択したプロキシVMにログインします。

+
Run Asクレデンシャルは、Windowsから提供されるデフォルトのドメイン管理者または組み込みのローカル管理者である必要があります。ワークグループユーザは、組み込みのローカル管理者アカウントを使用できます。

. [プロキシクレデンシャル]*セクションで*[追加]*を選択して、プロキシとして使用するVMを追加します。
. [Proxy VM]ダイアログボックスで、情報を入力し、*[Save]*を選択します。



NOTE: ESXiホストからプロキシVMを削除する前に、SnapCenter Plug-in for VMware vSphere UIからプロキシVMを削除する必要があります。
