---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere_01.html 
keywords:  
summary:  
---
= SnapCenter Plug-in for VMware vSphere を導入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter の機能を使用して仮想マシン、データストア、およびアプリケーションと整合性のあるデータベースを保護するには、 SnapCenter Plug-in for VMware vSphere を導入する必要があります。
。 link:scpivs44_download_the_ova_open_virtual_appliance.html["Open Virtual Appliance（OVA；オープン仮想アプライアンス）のダウンロード"^] ページに、OVAファイルをダウンロードする手順が記載されています。

. VMware vCenter 7.0.3以降のバージョンでは、の手順に従います link:scpivs44_download_the_ova_open_virtual_appliance.html["Open Virtual Appliance（OVA；オープン仮想アプライアンス）のダウンロード"^] をクリックしてvCenterに証明書をインポートします。
. ブラウザから VMware vSphere vCenter にアクセスします。
+

NOTE: IPv6 HTML Web クライアントの場合は、 Chrome または Firefox のいずれかを使用する必要があります。

. VMware vCenter Single Sign-Onページにログインします。
. ナビゲーションペインで、データセンター、フォルダ、クラスタ、ホストなどの仮想マシンの有効な親オブジェクトであるインベントリオブジェクトを右クリックし、[OVFテンプレートの展開*]を選択してVMware導入ウィザードを開始します。
. [Select an OVF template*](OVF テンプレートの選択 ) ページで '.ova ファイルの場所 ( 次の表のとおり ) を指定し '[*Next*]( 次へ ) をクリックします
+
|===
| このウィザードのページ | 操作 


| 名前とフォルダを選択します | VM または vApp の一意の名前を入力し、導入先を選択します。 


| リソースを選択します | 導入した VM テンプレートを実行するリソースを選択します。 


| 詳細を確認します | 「 .ova 」テンプレートの詳細を確認します。 


| 使用許諾契約 | [I accept all license agreements * ] のチェックボックスをオンにします。 


| ストレージを選択します | 導入した OVF テンプレートのファイルを保存する場所と方法を定義します。 


| ネットワークを選択します | 送信元ネットワークを選択し、宛先ネットワークにマッピングします。 


| テンプレートをカスタマイズします  a| 
「既存の vCenter に登録」に vCenter クレデンシャルを入力します。Create SnapCenter Plug-in for VMware vSphere credentials * で、 SnapCenter Plug-in for VMware vSphere のクレデンシャルを入力します。


NOTE: 指定するユーザ名とパスワードを書き留めます。SnapCenter Plug-in for VMware vSphere の設定をあとから変更する場合は、これらのクレデンシャルを使用する必要があります。

[ネットワークプロパティの設定]セクションで、ネットワーク情報を入力します。[Setup Date and Time]*セクションで、vCenterが配置されているタイムゾーンを選択します。



| 完了の準備が完了しました | ページを確認して、 [ 完了 ] をクリックします。 
|===
+

NOTE: すべてのホストに IP アドレスが設定されている必要があります（ FQDN ホスト名はサポートされません）。展開操作では、展開前に入力が検証されません。

. SnapCenter Plug-in for VMware vSphereを導入したVMに移動し、*[概要]*タブをクリックし、*[電源オン]*ボックスをクリックしてSnapCenter Plug-in for VMware vSphereを起動します。
. SnapCenter Plug-in for VMware vSphereの電源投入時に、導入したSnapCenter Plug-in for VMware vSphereを右クリックし、*[ゲストOS ]*を選択して*[VMwareツールのインストール]*をクリックします。
+
導入が完了するまでに数分かかることがあります。SnapCenter Plug-in for VMware vSphereの電源がオンになると導入が成功したことが通知され、VMware Toolsがインストールされ、SnapCenter Plug-in for VMware vSphereへのログインを求める画面が表示されます。

+
画面に、SnapCenter Plug-in for VMware vSphereの導入先のIPアドレスが表示されます。IPアドレスをメモします。SnapCenter Plug-in for VMware vSphereの設定を変更する場合は、SnapCenter Plug-in for VMware vSphere管理GUIにログインする必要があります。

. 導入画面に表示されたIPアドレスで導入ウィザードで指定したクレデンシャルを使用してSnapCenter Plug-in for VMware vSphere管理GUIにログインし、SnapCenter Plug-in for VMware vSphereがvCenterに正常に接続されて有効になっていることをダッシュボードで確認します。
+
の形式を使用します `\https://<appliance-IP-address>:8080` をクリックして管理GUIにアクセスします。

+
導入時に設定したadminユーザ名とパスワード、およびメンテナンスコンソールを使用して生成されたMFAトークンを使用してログインします。

. vCenter HTML5 クライアントにログインし、ツールバーの * メニュー * をクリックして、 * SnapCenter Plug-in for VMware vSphere * を選択します

