---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: バックアップリソースグループを作成、変更、削除したり、リソースグループに対してバックアップ処理を実行したりできます。 
---
= リソースグループの管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
バックアップリソースグループを作成、変更、削除したり、リソースグループに対してバックアップ処理を実行したりできます。


NOTE: Virtual Storage Console（VSC）では、リソースグループはバックアップジョブと呼ばれます。



== リソースグループに対する処理の一時停止と再開

スケジュールされた処理がリソースグループで開始されないように一時的に無効にすることができます。これらの処理は、必要に応じてあとで有効にすることができます。

.手順
. SCVプラグインの左側のナビゲーションペインで、*[Resource Groups]*を選択し、リソースグループを選択して*[Suspend]*を選択します（または*[Resume]*を選択します）。
. 確認ボックスで* OK *を選択して確定します。


.終了後
[Resource Groups]ページで、一時停止したリソースのジョブステータスはです `Under_Maintenance`。[Job Status]列が表示されるまで、表を右にスクロールしなければならない場合があります。

バックアップ処理が再開されると、[Job Status]がに変わります `Production`。



== リソースグループの変更

vCenterでリソースグループ内のリソースの削除や追加、ポリシーの適用解除や適用、スケジュールの変更、その他のリソースグループオプションの変更を行うことができます。

.タスクの内容
リソースグループの名前を変更する場合は、VM、データストア、ポリシー、バックアップ、またはリソースグループの名前に次の特殊文字を使用しないでください。

%&*$#@！\ / ： * ？"<> - | ； ' 、。

アンダースコア（_）を使用できます。

.手順
. SCVプラグインの左側のナビゲーションペインで、*[Resource Groups]*を選択し、リソースグループを選択して*[Edit]*を選択します。
. [リソースグループの編集]*ウィザードの左側のリストで、変更するカテゴリを選択し、変更内容を入力します。
+
複数のカテゴリに変更を加えることができます。このオプションでは、保護されたセカンダリリソースを編集することもできます。

. [概要]ページが表示されるまで[次へ]*を選択し、*[完了]*を選択します。




== リソースグループの削除

リソースグループ内のリソースを保護する必要がなくなった場合は、vCenterでリソースグループを削除できます。vCenterからSnapCenter Plug-in for VMware vSphereを削除する前に、すべてのリソースグループを削除する必要があります。

.タスクの内容
リソースグループの削除処理はすべて強制削除として実行されます。削除処理を実行すると、vCenterリソースグループからすべてのポリシーが解除され、リソースグループがSnapCenter Plug-in for VMware vSphereから削除され、リソースグループのすべてのバックアップとSnapshotが削除されます。


NOTE: SnapVault関係では、最後のSnapshotは削除できないため、リソースグループは削除できません。SnapVault関係の一部であるリソースグループを削除する前に、OnCommand System ManagerまたはONTAP CLIを使用してSnapVault関係を削除してから、最後のSnapshotを削除する必要があります。

.手順
. SCVプラグインの左側のナビゲーションペインで、*[Resource Groups]*を選択し、リソースグループを選択して*[Delete]*を選択します。
. [Delete resource group]*確認ボックスで、*[OK]*を選択して処理を確定します。

