---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere_01.html 
keywords:  
summary:  
---
= SnapCenter Plug-in for VMware vSphereの導入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenterの機能を使用して仮想マシン上のVM、データストア、アプリケーションと整合性のあるデータベースを保護するには、SnapCenter Plug-in for VMware vSphereを導入する必要があります。ページには、 link:scpivs44_download_the_ova_open_virtual_appliance.html["Open Virtual Appliance（OVA；オープン仮想アプライアンス）のダウンロード"^] OVAファイルをダウンロードする手順が記載されています。

. VMware vCenter 7.0.3以降のバージョンの場合は、の手順に従って、 link:scpivs44_download_the_ova_open_virtual_appliance.html["Open Virtual Appliance（OVA；オープン仮想アプライアンス）のダウンロード"^] 証明書をvCenterにインポートします。
. ブラウザで、VMware vSphere vCenterに移動します。
+

NOTE: IPv6アドレスのHTML Webクライアントの場合は、ChromeまたはFirefoxを使用する必要があります。

. VMware vCenter Single Sign-Onページにログインします。
. ナビゲーションペインで、データセンター、フォルダ、クラスタ、ホストなどの仮想マシンの有効な親オブジェクトであるインベントリオブジェクトを右クリックし、[OVFテンプレートの展開*]を選択してVMware導入ウィザードを開始します。
. [Select an OVF template*（OVFテンプレートの選択）]ページで、ファイルの場所（次の表を参照）を指定し `.ova`、[* Next（次へ）]*を選択します。
+
|===
| このウィザードのページ | 操作 


| 名前とフォルダを選択 | VMまたはvAppの一意の名前を入力し、導入先を選択します。 


| リソースを選択 | 導入したVMテンプレートを実行するリソースを選択します。 


| 詳細の確認 | テンプレートの詳細を確認します `.ova` 。 


| 使用許諾契約書 | [I accept all license agreements * ] のチェックボックスをオンにします。 


| ストレージの選択 | 導入したOVFテンプレートのファイルの保存場所と保存方法を定義 


| ネットワークの選択 | 送信元ネットワークを選択し、宛先ネットワークにマッピングします。 


| テンプレートのカスタマイズ  a| 
「既存の vCenter に登録」に vCenter クレデンシャルを入力します。Create SnapCenter Plug-in for VMware vSphere credentials * で、 SnapCenter Plug-in for VMware vSphere のクレデンシャルを入力します。


NOTE: 指定したユーザ名とパスワードをメモしておきます。SnapCenter Plug-in for VMware vSphereの設定をあとで変更する場合は、これらのクレデンシャルを使用する必要があります。

[ネットワークプロパティの設定]セクションで、ネットワーク情報を入力します。[Setup Date and Time]*セクションで、vCenterが配置されているタイムゾーンを選択します。



| 選択内容の確認 | ページを確認し、*[終了]*を選択します。 
|===
+

NOTE: すべてのホストにIPアドレスを設定する必要があります（FQDNホスト名はサポートされません）。導入処理では、導入前に入力した内容は検証されません。

. SnapCenter Plug-in for VMware vSphereを導入したVMに移動し、*[概要]*タブを選択し、*[電源オン]*ボックスを選択してSnapCenter Plug-in for VMware vSphereを起動します。
. SnapCenter Plug-in for VMware vSphereの電源投入時に、導入したSnapCenter Plug-in for VMware vSphereを右クリックし、*[ゲストOS ]*を選択して*[VMwareツールのインストール]*を選択します。
+
導入が完了するまでに数分かかることがあります。SnapCenter Plug-in for VMware vSphereの電源がオンになると導入が成功したことが通知され、VMware Toolsがインストールされ、SnapCenter Plug-in for VMware vSphereへのログインを求める画面が表示されます。

+
画面に、SnapCenter Plug-in for VMware vSphereの導入先のIPアドレスが表示されます。IPアドレスをメモします。SnapCenter Plug-in for VMware vSphereの設定を変更する場合は、SnapCenter Plug-in for VMware vSphere管理GUIにログインする必要があります。

. 導入画面に表示されたIPアドレスで導入ウィザードで指定したクレデンシャルを使用してSnapCenter Plug-in for VMware vSphere管理GUIにログインし、SnapCenter Plug-in for VMware vSphereがvCenterに正常に接続されて有効になっていることをダッシュボードで確認します。
+
管理GUIにアクセスするには、の形式を使用し `\https://<appliance-IP-address>:8080` ます。

+
導入時に設定したadminユーザ名とパスワード、およびメンテナンスコンソールを使用して生成されたMFAトークンを使用してログインします。

. vCenter HTML5クライアントにログインし、ツールバーの*[メニュー]*を選択し、*[VMware vSphere用SnapCenterプラグイン]*を選択します。

