---
sidebar: sidebar 
permalink: scpivs44_information_not_displayed_after_upgrading_to_a_new_patch_of_the_same_release.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere を同じリリースの新しいパッチにアップグレードすると、ダッシュボードとジョブモニタに最近のジョブやその他の情報が表示されないことがあります。 
---
= 同じリリースの新しいパッチにアップグレードしたあとに情報が表示されない
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere を同じリリースの新しいパッチにアップグレードすると、ダッシュボードとジョブモニタに最近のジョブやその他の情報が表示されないことがあります。

同じリリースの新しいパッチにアップグレードする場合は、 vCenter Web Server で SnapCenter Plug-in for VMware vSphere キャッシュをクリアし、アップグレードまたは登録を行う前にサーバを再起動する必要があります。

プラグインキャッシュがクリアされない場合、次のシナリオではダッシュボードとジョブモニタに最新のジョブは表示されません。

* vCenter を使用して SnapCenter Plug-in for VMware vSphere を導入し、その後同じリリースのパッチにアップグレードしました。
* SnapCenter VMware仮想アプライアンスはvCenter 1に導入しました。その後、このSnapCenter Plug-in for VMware vSphereを新しいvCenter2に登録しました。SnapCenter Plug-in for VMware vSphereの新しいインスタンスがパッチを使用して作成され、vCenter1に登録されます。ただし、vCenter1にはパッチが適用されていない最初のSnapCenter Plug-in for VMware vSphereのプラグインがキャッシュされているため、キャッシュをクリアする必要があります。


キャッシュは、サーバオペレーティングシステムのタイプに基づいて次の場所に格納されます。

* vCenter Server Linux Appliance の略
+
/etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity / です

* Windows OS の場合
+
`%PROGRAMFILES%/VMware/vSphere client/vc-packages/vsphere-client-serenity/`





== キャッシュをクリアする前にすでにアップグレードしている場合は回避策

. SnapCenter Plug-in for VMware vSphere管理GUIにログインします。
+
IPアドレスは、SnapCenter Plug-in for VMware vSphereの導入時に表示されます。

. 左側のナビゲーションペインで * Configuration * をクリックし、 * Plug-in Details * セクションのサービスオプションをクリックしてプラグインを無効にします。
+
SnapCenter Plug-in for VMware vSphereサービスが無効になり、vCenterで拡張機能の登録が解除されます。

. を探します `vsphere-client-serenity` フォルダを選択し、を選択します `com.netapp.scv.client-<release-number>` フォルダを削除します。
+
フォルダ名はリリースごとに変更されます。

. vCenter Server を再起動します。
. VMware vSphere Clientにログインします。
. 左側のナビゲーションペインで * Configuration * をクリックし、 * Plug-in Details * セクションのサービスオプションをクリックしてプラグインを有効にします。
+
SnapCenter Plug-in for VMware vSphereサービスが有効になり、vCenterに拡張機能が登録されます。


