---
sidebar: sidebar 
permalink: scpivs44_disable_and_enable_plugin.html 
keywords:  
summary: SnapCenter のデータ保護機能が不要になった場合は、 SnapCenter VMware プラグインの設定を変更する必要があります。たとえば、テスト環境にプラグインを導入した場合は、その環境で SnapCenter 機能を無効にして、本番環境で有効にする必要があります。 
---
= SnapCenter Plug-in for VMware vSphere を無効にして有効にします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


SnapCenter のデータ保護機能が不要になった場合は、 SnapCenter VMware プラグインの設定を変更する必要があります。たとえば、テスト環境にプラグインを導入した場合は、その環境で SnapCenter 機能を無効にして、本番環境で有効にする必要があります。

.作業を開始する前に
* 管理者権限が必要です。
* 実行中の SnapCenter ジョブがないことを確認します。


SnapCenter VMware プラグインを無効にすると、すべてのリソースグループが中断され、プラグインが vCenter で拡張機能として登録解除されます。

SnapCenter VMware プラグインを有効にすると、プラグインが vCenter で拡張機能として登録され、すべてのリソースグループが本番モードになり、すべてのスケジュールが有効になります。

.手順
. オプション： SnapCenter VMware プラグインの MySQL リポジトリを新しい仮想アプライアンスにリストアする場合にバックアップします。
+
link:scpivs44_back_up_the_snapcenter_plug-in_for_vmware_vsphere_mysql_database.html["SnapCenter Plug-in for VMware vSphere MySQL データベースをバックアップします"]。

. 「 https://<OVA-IP-address>:8080` 」の形式で、 SnapCenter VMware プラグイン管理 GUI にログインします。
+
プラグインの導入時に、 SnapCenter VMware プラグインの IP が表示されます。

. 左側のナビゲーションペインで * Configuration * をクリックし、次に * Plug-in Details * セクションの Service オプションの選択を解除してプラグインを無効にします。
. 選択を確定します。
+
** SnapCenter VMware プラグインのみを使用して VM 整合性のあるバックアップを実行した場合
+
プラグインが無効になっており、これ以上の操作は必要ありません。

** SnapCenter VMware プラグインを使用してアプリケーションと整合性のあるバックアップを実行した場合
+
プラグインが無効になっているため、さらにクリーンアップする必要があります。

+
... VMware vSphere にログインします。
... VM の電源をオフにします。
... 左側のナビゲータ画面で、 SnapCenter VMware プラグインのインスタンス（仮想アプライアンスの導入時に使用された「 .ova 」ファイルの名前）を右クリックし、「ディスクから削除」を選択します。
... SnapCenter にログインして、 vSphere ホストを削除します。





