---
sidebar: sidebar 
permalink: scpivs44_minimum_ontap_privileges_required.html 
keywords:  
summary: 必要な最小 ONTAP 権限は、データ保護に使用する SnapCenter プラグインによって異なります。 
---
= ONTAP 権限が必要です
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
必要な最小 ONTAP 権限は、データ保護に使用する SnapCenter プラグインによって異なります。


NOTE: SnapCenter Plug-in for VMware（SCV）5.0以降では、SCVへのカスタマイズされたロールベースアクセスを持つすべてのONTAPユーザに対して、HTTPおよびONTAPIタイプのアプリケーションをユーザのログイン方法として追加する必要があります。これらのアプリケーションにアクセスできないと、バックアップは失敗します。ONTAPユーザのログイン方法の変更を認識するには、SCVサービスを再起動する必要があります。



== 必要な最小 ONTAP 権限

すべての SnapCenter プラグインには、次の最小権限が必要です。

|===


| フルアクセスコマンド： ONTAP 8.3 以降で必要な最小権限 


| cluster identity show の実行 


| event generate-autosupport-log を指定します 


| ジョブ履歴の表示
ジョブの表示
ジョブが停止しました 


| lun lun create lun delete lun igroup add lun igroup create lun igroup delete lun igroup rename lun igroup rename lun igroup show lun mapping add-reporting-nodes lun mapping create lun mapping remove-reporting-nodes lun mapping show lun modify lun move-in-volume LUN offline LUN online lun persistent-reservation clear lun resize lun serial lun show をクリックします 


| snapmirror list-destinations snapmirror policy add-rule snapmirror policy modify -rule snapmirror policy show snapmirror restore snapmirror show -history snapmirror update snapmirror update-ls-set 


| バージョン 


| volume clone create を実行します
volume clone show を実行します
ボリュームクローンスプリット開始
ボリュームクローンスプリットは停止します
volume create を実行します
volume delete
ボリュームを削除します
volume file clone create を実行します
volume file show-disk-usage
ボリュームはオフラインです
ボリュームはオンラインです
volume modify を使用します
volume qtree create を実行します
volume qtree delete
volume qtree modify の略
volume qtree show の略
ボリュームの制限
volume show のコマンドです
volume snapshot create を実行します
ボリューム Snapshot の削除
volume snapshot modify の実行
ボリューム Snapshot の名前が変更されます
ボリューム Snapshot リストア
ボリューム Snapshot の restore-file
volume snapshot show の実行
ボリュームのアンマウント 


| vserver cifs share create vserver cifs share create vserver cifs share delete vserver cifs shadowcopy show vserver cifs share show vserver cifs share show vserver cifs show vserver export-policy vserver export-policy vserver export-policy vserver export-policy create vserver export-policy rule create vserver export-policy rule create vserver export-policy rule show vserver export-policy rule show vserver iscsi vserver iscsi vserver iscsi connection show vserver show network interface network interface failover-groups network interface show を実行します 
|===
|===
| 読み取り専用コマンド： ONTAP 8.3 以降で必要な最小権限 


| SVM SVMピア 
|===

NOTE: サポートされていないvServerコマンドに関する警告メッセージは無視してかまいません。



== ONTAP に関するその他の情報

* ONTAP 8.2.x を実行している場合：
+
SnapCenter Plug-in for VMware vSphere の処理を実行するための適切な権限を取得するには、 Storage VM の「 vsadmin 」としてログインする必要があります。

* ONTAP 8.3 以降を実行している場合：
+
「 vsadmin 」としてログインするか、上記の表に記載された最小権限を持つロールでログインする必要があります。

* ユーザロールを作成および管理するには、クラスタ管理者である必要があります。ユーザは、クラスタStorage VMまたはStorage VMに関連付けることができます。
* SnapMirrorビジネス継続性（SM-BC）機能を使用するには、ONTAP 9.12.1以降のバージョンが必要です。
* 改ざん防止スナップショット（TPS）機能を使用するには、次の手順を実行します。
+
** SANにはONTAP 9.13.1以降のバージョンが必要です。
** NFSにはONTAP 9.12.1以降のバージョンが必要です。





NOTE: ONTAPバージョン9.11.1以降の場合、ONTAPクラスタとの通信にはREST APIを使用します。ONTAPユーザは、httpアプリケーションを有効にしておく必要があります。ただし、ONTAP REST APIで問題が見つかった場合は、設定キー「force_zapi」を使用して従来のZAPIワークフローに切り替えることができます。設定APIを使用してこのキーを追加または更新し、trueに設定する必要がある場合があります。技術情報アーティクル、 https://kb.netapp.com/mgmt/SnapCenter/How_to_use_RestAPI_to_edit_configuration_parameters_in_SCV["RestAPIを使用してSCVの設定パラメータを編集する方法"]。
