---
sidebar: sidebar 
permalink: scpivs44_download_job_logs.html 
keywords:  
summary: 'ジョブログは、SnapCenter VMware vSphere Clientのダッシュボードにある[Job Monitor]タブからダウンロードできます。' 
---
= ジョブログをダウンロード
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ジョブログは、SnapCenter VMware vSphere Clientのダッシュボードにある[Job Monitor]タブからダウンロードできます。

VMware vSphere Clientの使用中に予期しない動作が発生した場合は、ログファイルを使用して原因を特定し、問題を解決できます。


NOTE: ジョブログの保持のデフォルト値は30日です。ジョブの保持のデフォルト値は90日です。設定された保持期間よりも古いジョブログおよびジョブは、6時間ごとにパージされます。設定REST APIを使用して、ジョブとジョブログを保持する期間を変更できます `jobs/cleanup` 。パージスケジュールは変更できません。

.手順
. vCenterクライアントのショートカットページで、SnapCenter Plug-in for VMware vSphere（SCV）を選択します。
. SCVの左側のナビゲーションペインで、*[ダッシュボード]*>*[ジョブモニタ]*を選択します。
. ジョブモニタのタイトルバーでダウンロードアイコンを選択します。
+
アイコンを表示するには、右にスクロールしなければならない場合があります。

+
ジョブをダブルクリックして [ ジョブの詳細 ] ウィンドウにアクセスし、 [ ジョブログのダウンロード ] をクリックすることもできます。



.結果
ジョブログは、SnapCenter Plug-in for VMware vSphereが導入されているLinux VMホストに保存されます。デフォルトのジョブログの場所はです `/var/log/netapp`。

ジョブログをダウンロードしようとしたが、エラーメッセージ内のという名前のログファイルが削除されている場合は、次のエラーが発生することがあります。 `HTTP ERROR 500 Problem accessing /export-scv-logs`このエラーを修正するには、エラーメッセージで指定されたファイルのファイルアクセスステータスと権限を確認し、アクセスの問題を修正します。
