---
sidebar: sidebar 
permalink: scpivs44_restore_vmdks_from_backups.html 
keywords:  
summary: プライマリまたはセカンダリバックアップから、既存の VMDK をリストアしたり、削除または分離された VMDK をリストアしたりできます。 
---
= バックアップから VMDK をリストアする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
プライマリまたはセカンダリバックアップから、既存の VMDK をリストアしたり、削除または分離された VMDK をリストアしたりできます。

VM 上の 1 つ以上の仮想マシンディスク（ VMDK ）を同じデータストアにリストアできます。


TIP: NFS 環境でのリストア処理のパフォーマンスを向上させるには、 VMware アプリケーション vStorage API for Array Integration （ VAAI ）を有効にします。

.作業を開始する前に
* バックアップが存在している必要があります。
+
SnapCenter Plug-in for VMware vSphere を使用して VM のバックアップを作成しておく必要があります。

* VM が転送中でないことを確認する必要があります。
+
リストアする VM が vMotion または Storage vMotion の状態でないことを確認してください。



.このタスクについて
* VMDK が削除されるか VM から切断された場合は、リストア処理によって VMDK が VM に接続されます。
* VM が配置されている FabricPool のストレージ階層が使用できない場合、リストア処理が失敗することがあります。
* 接続処理とリストア処理は、デフォルトの SCSI コントローラを使用して VMDK に接続します。NVMe コントローラを搭載した VM に接続されている VMDK がバックアップされますが、接続処理およびリストア処理では、 SCSI コントローラを使用して再接続されます。


.手順
. VMware vSphere Web Client の GUI で、ツールバーの * メニュー * をクリックし、ドロップダウンリストから * VMs and Templates * を選択します。
. 左側のナビゲーションペインで、 VM を右クリックし、ドロップダウンリストから「 * NetApp SnapCenter * 」を選択してから、セカンダリドロップダウンリストから「 * Restore * 」を選択します。
. リストア * ウィザードのバックアップの選択ページで、リストア元のバックアップ・コピーを選択します。
+
特定のバックアップ名またはバックアップ名の一部を検索するか、フィルタアイコンをクリックして日時の範囲を選択し、 VMware スナップショットの有無、マウントするバックアップの有無を選択して、バックアップリストをフィルタリングすることができます。 プライマリまたはセカンダリの場所を指定できます。[OK] をクリックしてウィザードに戻ります。

. ［ * スコープの選択 * ］ ページで、リストア先を選択します。
+
|===
| リストア先 | リストア先を指定 ... 


| 元のデータストア | ドロップダウン・リストから * 特定のディスク * を選択し、 * 次へ * をクリックします。データストア選択テーブルで、 VMDK を選択または選択解除できます。 


| 別の場所にある代替データストア | デスティネーションデータストアをクリックして、リストから別のデータストアを選択します。 
|===
. [ 場所の選択 * ] ページで、リストアする Snapshot コピー（プライマリまたはセカンダリ）を選択します。
. [ 概要 ] ページを確認し、 [ 完了 ] をクリックします。
. オプション：画面下部の * 最近のタスク * をクリックして、処理の進行状況を監視します。
. 更新された情報を表示するには、画面を更新します。

