---
sidebar: sidebar 
permalink: scpivs44_restore_vmdks_from_backups.html 
keywords:  
summary: 従来のVMまたはVVol VMのプライマリバックアップまたはセカンダリバックアップから、既存のVMDK、または削除または接続解除したVMDKをリストアできます。 
---
= バックアップからのVMDKのリストア
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
従来のVMまたはVVol VMのプライマリバックアップまたはセカンダリバックアップから、既存のVMDK、または削除または接続解除したVMDKをリストアできます。

VM上の1つ以上の仮想マシンディスク（VMDK）を同じデータストアにリストアできます。


TIP: NFS環境でのリストア処理のパフォーマンスを向上させるには、VMwareアプリケーションのvStorage API for Array Integration（VAAI）を有効にします。

.開始する前に
* バックアップが存在している必要があります。
+
SnapCenter Plug-in for VMware vSphereを使用してVMのバックアップを作成しておく必要があります。

* VMは転送中ではありません。
+
リストアするVMがvMotionまたはStorage vMotionの状態でないことを確認します。



.タスクの内容
* VMDKがVMから削除されたり切断されたりすると、リストア処理によってVMDKがVMに接続されます。
* VMが配置されているFabricPoolのストレージ階層を使用できない場合、リストア処理が失敗することがあります。
* 接続処理とリストア処理では、デフォルトのSCSIコントローラを使用してVMDKが接続されます。ただし、NVMeディスクを使用してVMに接続されたVMDKをバックアップする場合は、可能な場合はNVMeコントローラが接続処理とリストア処理で使用されます。


.手順
. VMware vSphere ClientのGUIで、ツールバーの*メニュー*をクリックし、ドロップダウンリストから* VMs and Templates *を選択します。
. 左側のナビゲーションペインで、VMを右クリックし、ドロップダウンリストから* SnapCenter Plug-in for VMware vSphere *を選択し、2番目のドロップダウンリストから*[リストア]*を選択します。
. リストア * ウィザードのバックアップの選択ページで、リストア元のバックアップ・コピーを選択します。
+
特定のバックアップ名またはバックアップ名の一部を検索するか、バックアップリストをフィルタすることができます。フィルタアイコンをクリックして、日時の範囲、VMwareスナップショットを含むバックアップの有無、マウントされたバックアップの有無、プライマリまたはセカンダリの場所を選択します。[OK] をクリックしてウィザードに戻ります。

. ［ * スコープの選択 * ］ ページで、リストア先を選択します。
+
|===
| リストア先 | リストア先を指定 ... 


| 元のデータストア | ドロップダウン・リストから * 特定のディスク * を選択し、 * 次へ * をクリックします。[Datastore]選択テーブルで、VMDKを選択または選択解除できます。 


| 別の場所にある別のデータストア | デスティネーションデータストアをクリックし、リストから別のデータストアを選択します。 
|===
. [場所の選択]*ページで、リストアするSnapshot（プライマリまたはセカンダリ）を選択します。
. [ 概要 ] ページを確認し、 [ 完了 ] をクリックします。
. オプション：画面下部の * 最近のタスク * をクリックして、処理の進行状況を監視します。
. 更新された情報を表示するには、画面を更新します。

