---
sidebar: sidebar 
permalink: scpivs44_mount_a_backup.html 
keywords:  
summary: バックアップ内のファイルにアクセスする必要がある場合は、バックアップから従来のデータストアをマウントできます。バックアップは、バックアップが作成されたESXiホスト、または同じタイプのVMおよびホスト構成を使用する別のESXiホストにマウントできます。データストアはホストに複数回マウントできます。 
---
= バックアップのマウント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
バックアップ内のファイルにアクセスする必要がある場合は、バックアップから従来のデータストアをマウントできます。バックアップは、バックアップが作成されたESXiホスト、または同じタイプのVMおよびホスト構成を使用する別のESXiホストにマウントできます。データストアはホストに複数回マウントできます。

VVOLデータストアはマウントできません。

.開始する前に
* 代替ESXiホストがストレージに接続できることを確認する
+
代替ESXiホストにマウントする場合は、代替ESXiホストがストレージに接続できること、および次の要件を満たしていることを確認する必要があります。

+
** UIDとGIDが元のホストと同じ
** SnapCenter Plug-in for VMware vSphere仮想アプライアンスのバージョンが元のホストと同じである


* iSCSIプロトコルを使用する場合は、ストレージシステムのイニシエータがESXiホストにマッピングされていることを確認してください。NVMeプロトコルを使用する場合は、コントローラを追加して必要なサブシステムをESXiホストにマッピングします。
* 古いLUN /ネームスペースをクリーンアップ
+
ESXiホストで検出できる一意のLUN /ネームスペースはデータストアごとに1つだけであるため、複数検出された場合は処理が失敗します。これは、前のマウント処理が完了する前にマウント処理を開始した場合、LUN /ネームスペースを手動でクローニングした場合、またはアンマウント処理でストレージからクローンが削除されなかった場合に発生することがあります。複数のクローンが検出されないようにするには、ストレージ上の古いLUN/ネームスペースをすべてクリーンアップする必要があります。



.タスクの内容
データストアが配置されているFabricPoolのストレージ階層が使用できない場合、マウント処理が失敗することがあります。

.手順
. VMware vSphere Clientのショートカットページで、*[ストレージ]*を選択します。
. データストアを右クリックし、* SnapCenter Plug-in for VMware vSphere *>*[バックアップのマウント]*を選択します。
. [データストアのマウント]*ページで、バックアップとバックアップの場所（プライマリまたはセカンダリ）を選択し、*[終了]*を選択します。
. オプション：データストアがマウントされたことを確認するには、次の手順を実行します。
+
.. ツールバーの*[メニュー]*を選択し、ドロップダウンリストから*[ストレージ]*を選択します。
.. 左側のナビゲーションペインで、マウントしたデータストアがリストの上部に表示されます。
+
ボリュームのクローニング時に新しいSnapshotが作成されないようにするには、SnapVaultボリュームのONTAPスケジュールをオフにします。既存のSnapshotは削除されません。




