---
sidebar: sidebar 
permalink: scpivs44_view_status_information.html 
keywords:  
summary: vSphere Clientのダッシュボードでステータス情報を確認できます。ステータス情報は1時間に1回更新されます。 
---
= ステータス情報の表示
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vSphere Clientのダッシュボードでステータス情報を確認できます。ステータス情報は1時間に1回更新されます。

.手順
. vCenterクライアントのショートカットページで、SnapCenter Plug-in for VMware vSphere（SCV）を選択します。
. SCVの左側のナビゲーションペインで、*[ダッシュボード]*>*[ステータス]*を選択します。
. 次の表に示す概要ステータス情報を表示するか、詳細を表示するリンクをクリックします。
+
|===
| このダッシュボードタイル… | 次の情報を表示します。 


 a| 
最近のジョブアクティビティ
 a| 
最新のバックアップ、リストア、およびマウントジョブが 3~5 つ実行されています。

** ジョブIDをクリックすると、そのジョブの詳細が表示されます。
** すべてのジョブの詳細については、 [ すべて表示 ] をクリックして [ ジョブモニタ ] タブに移動します。




 a| 
ジョブ
 a| 
選択した期間内に実行された各ジョブタイプ（バックアップ、リストア、マウント）の数。グラフのセクションにカーソルを合わせると、そのカテゴリの詳細が表示されます。



 a| 
最新の保護サマリ
 a| 
選択した期間内のプライマリ VM およびセカンダリ VM またはデータストアのデータ保護ステータスの概要。

** ドロップダウンメニューをクリックして、 * VMS * または * Datastores * を選択します。
** セカンダリストレージの場合は、 * SnapVault * または * SnapMirror * を選択します。
** グラフのセクションにカーソルを合わせると、そのカテゴリ内のVMまたはデータストアの数が表示されます。[成功]カテゴリには、各リソースの最新のバックアップが表示されます。
** 時間ウィンドウは、構成ファイルを編集して変更できます。デフォルトは7日です。詳細については、を参照してください link:scpivs44_customize_your_configuration.html["構成のカスタマイズ"]。
** 内部カウンタは、プライマリまたはセカンダリの各バックアップ後に更新されます。ダッシュボードタイルは6時間ごとに更新されます。更新時間は変更できません。注：ミラーバックアップ保護ポリシーを使用している場合は、保護の概要のカウンタが SnapMirror チャートではなく SnapVault の概要チャートに表示されます。




 a| 
構成
 a| 
SnapCenter Plug-in for VMware vSphere で管理されている各タイプのオブジェクトの総数。



 a| 
ストレージ
 a| 
Snapshot、SnapVault、SnapMirror Snapshotの総数と、生成されたプライマリSnapshotとセカンダリSnapshotに使用されているストレージ容量。折れ線グラフには、過去90日間のプライマリストレージとセカンダリストレージの日単位の消費量が表示されます。ストレージ情報は24時間ごとに午前1時8分に更新されます。ストレージ削減量は、プライマリストレージの物理容量に対する論理容量（Snapshotによる削減量とストレージ消費量の合計）の比率です。棒グラフはストレージ削減量を示しています。

グラフの線にカーソルを合わせると、1日ごとの詳細な結果が表示されます。

|===

