---
sidebar: sidebar 
permalink: scpivs44_mount_a_backup.html 
keywords:  
summary: バックアップ内のファイルにアクセスする必要がある場合は、バックアップから従来のデータストアをマウントできます。バックアップは、バックアップが作成された ESXi ホストにも、同じタイプの VM およびホスト構成を使用する代替 ESXi ホストにもマウントできます。データストアはホストに複数回マウントできます。 
---
= バックアップをマウント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
バックアップ内のファイルにアクセスする必要がある場合は、バックアップから従来のデータストアをマウントできます。バックアップは、バックアップが作成された ESXi ホストにも、同じタイプの VM およびホスト構成を使用する代替 ESXi ホストにもマウントできます。データストアはホストに複数回マウントできます。

VVOL データストアはマウントできません。

.作業を開始する前に
* 代替 ESXi ホストがストレージに接続できることを確認します
+
別の ESXi ホストにマウントする場合は、代替の ESXi ホストがストレージに接続可能で、次の条件を満たしていることを確認する必要があります。 ** 元のホストと同じ UID および GID ** 元のホストと同じバージョンの SnapCenter Plug-in for VMware vSphere 仮想アプライアンス

* ストレージイニシエータを ESXi にマッピングする
+
ストレージシステムのイニシエータが ESXi にマッピングされていることを確認します。

* 古い LUN をクリーンアップします
+
ESXi はデータストアごとに一意の LUN を 1 つしか検出できないため、複数検出された場合は処理が失敗します。この状況は、前回のマウント処理の終了前にマウント処理を開始した場合や、 LUN のクローンを手動で作成した場合、アンマウント処理中にクローンがストレージから削除されない場合に発生することがあります。複数のクローンが検出されないようにするには、ストレージ上の古い LUN をすべてクリーンアップする必要があります。



データストアが配置されている FabricPool のストレージ階層が使用できない場合、マウント処理が失敗することがあります。

.手順
. VMware vSphere Web Client で、ツールバーの * メニュー * をクリックし、ドロップダウンリストから * ストレージ * を選択します。
. データストアを右クリックし、ドロップダウンリストから「 * NetApp SnapCenter * 」を選択して、セカンダリドロップダウンリストから「 * Mount Backup * 」を選択します。
. [ データストアのマウント *] ページで、バックアップとバックアップの場所 ( プライマリまたはセカンダリ ) を選択し、 [ 完了 *] をクリックします。
. オプション：データストアがマウントされたことを確認するには、次の手順を実行します。
+
.. ツールバーの * メニュー * をクリックし、ドロップダウン・リストから * ストレージ * を選択します。
.. 左側のナビゲーションペインで、マウントしたデータストアがリストの上部に表示されます。
+
ONTAP スケジュールで保護されており、 SnapVault 8.3 を実行している SnapVault デスティネーションボリュームで接続処理またはマウント処理を実行すると、画面の接続またはマウントダイアログに余分な Snapshot コピーが表示される場合があります。これは、接続処理またはマウント処理で SnapVault デスティネーションボリュームのクローンを作成し、 ONTAP で新しい Snapshot コピーを作成することでボリュームを更新するためです。

+
ボリュームのクローニング時に新しい Snapshot コピーが作成されないようにするには、 SnapVault ボリュームの ONTAP スケジュールを無効にします。以前の既存の Snapshot コピーは削除されません。




