---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_from_vmdks.html 
keywords:  
summary: Windows ゲスト OS の VMDK から、 1 つ以上のファイルやフォルダをリストアできます。 
---
= VMDK からゲストのファイルとフォルダをリストアする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Windows ゲスト OS の VMDK から、 1 つ以上のファイルやフォルダをリストアできます。

.このタスクについて
デフォルトでは、接続された仮想ディスクは 24 時間使用可能であり、その後自動的に接続解除されます。ウィザードで、復元操作が完了したときにセッションを自動的に削除するように選択するか、またはゲストファイルの復元セッションをいつでも手動で削除するか、または [*Guest Configuration*] ページで時間を延長することができます。

ゲストファイルまたはフォルダのリストアのパフォーマンスは、リストアするファイルまたはフォルダのサイズとリストアするファイルまたはフォルダの数の 2 つの要因によって異なります。サイズの小さいファイルを大量にリストアする場合、リストアするデータセットが同じであれば、サイズの大きいファイルをリストアする場合に比べて、予想よりも時間がかかることがあります。


IMPORTANT: VM に対して同時に実行できる接続処理またはリストア処理は 1 つだけです。同じ VM で並行して接続処理やリストア処理を実行することはできません。


IMPORTANT: ゲストリストア機能を使用すると、システムと非表示のファイルを表示および復元したり、暗号化されたファイルを表示したりできます。既存のシステムファイルを上書きしたり、暗号化されたファイルを暗号化されたフォルダに復元したりしないでください。リストア処理中は、ゲストファイルの非表示、システム、および暗号化された属性はリストアされたファイルに保持されません。予約済みパーティションを表示または参照すると、原因でエラーが発生する場合があります。

.手順
. メニュー * をクリックし、ホストとクラスタ * メニューオプションを選択して VM を選択し、 * NetApp SnapCenter * を選択して、 * ゲストファイルのリストア * をクリックします。
. VMware vSphere Web Client で、セカンダリドロップダウンリストから「 * Guest File Restore * 」をクリックしてウィザードを開始します。
. [* リストア範囲 *] ページで、接続する仮想ディスクを含むバックアップを指定します。次の手順を実行します。
+
.. [* バックアップ名 * ] テーブルで、接続する仮想ディスクを含むバックアップを選択します。
.. * VMDK * テーブルで、リストアするファイルまたはフォルダが格納されている仮想ディスクを選択します。
.. [ * 場所 * ] テーブルで、接続する仮想ディスクの場所（プライマリまたはセカンダリ）を選択します。


. [*Guest Details*] ページで、次の操作を行います。
+
.. 仮想ディスクの接続先を選択します。
+
|===
| 選択するオプション | 条件 


| ゲスト VM を使用します  a| 
ウィザードを開始する前に右クリックした VM に仮想ディスクを接続し、右クリックした VM のクレデンシャルを選択します。


NOTE: VM のクレデンシャルを作成しておく必要があります。



| ゲストファイルリストアプロキシ VM を使用します  a| 
仮想ディスクをプロキシ VM に接続し、プロキシ VM を選択します。


NOTE: 接続とリストア処理を開始する前に、プロキシ VM を設定する必要があります。

|===
.. [ 電子メール通知を送信する *] オプションを選択します。
+
接続処理が完了し、仮想ディスクが使用可能になったときに通知を受け取るには、このオプションが必要です。通知 E メールには、仮想ディスク名、 VM 名、および新たに VMDK に割り当てられたドライブレターが含まれます。

+

TIP: ゲストファイルのリストアは非同期処理であり、ゲストセッションを確立するための遅延時間が発生する可能性があるため、このオプションを有効にします。

+
このオプションでは、 vCenter で VMware vSphere Web Client をセットアップするときに設定した E メール設定を使用します。



. 概要を確認し、 [ 完了 ] をクリックします。
+
「 * 完了」をクリックする前に、ウィザードの任意のページに戻って情報を変更できます。

. 接続処理が完了するまで待ちます。
+
処理の進捗状況はダッシュボードジョブモニタで確認することも、 E メール通知が送信されるまで待つこともできます。

. 接続された仮想ディスクからリストアするファイルを検索するには、 [ * メニュー ] > [VMware Plug-in for SnapCenter vSphere* ] をクリックし、左側の [ ナビゲーター ] ペインで [ * ゲストファイルのリストア * ] をクリックして、 [ ゲスト構成 * ] タブを選択します。
+
[Guest Session Monitor] テーブルで、 [*...] をクリックすると、セッションに関する追加情報を表示できます。 * 右側の列に表示されます。

. 通知メールに記載されている仮想ディスクのゲストファイルリストアセッションを選択します。
+
すべてのパーティションには、システム予約パーティションを含むドライブ文字が割り当てられます。VMDK に複数のパーティションがある場合は、ゲストファイルの参照ページの上部にあるドライブフィールドのドロップダウンリストでドライブを選択することにより、特定のドライブを選択できます。

. ファイルの参照 * アイコンをクリックして、仮想ディスク上のファイルとフォルダのリストを表示します。
+
フォルダをダブルクリックして個々のファイルを参照および選択すると、実行時にフェッチ操作が実行されるため、ファイルのリストの読み込み中に遅延が発生する可能性があります。

+
参照を簡単にするために、検索文字列のフィルタを使用できます。フィルタでは大文字と小文字が区別され、 Perl 式ではスペースは使用されません。デフォルトの検索文字列は「 . 」です。次の表に、 Perl 検索式の例を示します。

+
|===
| この式 | 検索対象 ... 


| 。 | 改行文字以外の任意の文字。 


| * | 任意の文字列。これがデフォルトです。 


| A | 文字 a 


| AB | 文字列 ab 。 


| a [ 縦棒 ] b | a または b のいずれかを指定します 


| A * | 文字 a... の 0 個以上のインスタンス 


| A+ | 文字 a... の 1 つ以上のインスタンス 


| A | 文字 a... の 0 または 1 つのインスタンス 


| ｛ x ｝ | 文字 a... のインスタンス x 個を正確に指定します 


| ｛ x 、 ｝ | 文字 a... の少なくとも x 個のインスタンス 


| a ｛ x 、 y ｝ | 文字 A のインスタンスの少なくとも x 個と、最大 y 個の数字。 


| \ | 特殊文字をエスケープします。 
|===
+
[ ゲストファイルの参照 ] ページには、他のすべてのファイルとフォルダに加えて、すべての隠しファイルと隠しフォルダが表示されます。

. 復元する 1 つまたは複数のファイルまたはフォルダを選択し、 * リストア場所の選択 * をクリックします。
+
リストアするファイルとフォルダが Selected File(s) テーブルに表示されます。

. [ リストア先の選択 *] ページで、次の項目を指定します。
+
|===
| オプション | 説明 


| パスにリストアします | 選択したファイルがリストアされるゲストへの UNC 共有パスを入力してください。IPv4 の例： \\10.60.136.65\c$'IPv6 の例： \\fd20-8b1e-b255-832e--61.ipv6-literal.net\C\restore` 


| 元のファイルが存在する場合  a| 
リストア先にリストア対象のファイルまたはフォルダがすでに存在する場合に実行する処理を選択します。 Always overwrite または always skip 。


NOTE: フォルダがすでに存在する場合は、そのフォルダの内容が既存のフォルダにマージされます。



| リストアが正常に完了したら、ゲストセッションを切断します | リストア処理の完了時にゲストファイルのリストアセッションを削除する場合は、このオプションを選択します。 
|===
. [* リストア ] をクリックします。
+
リストア処理の進捗状況はダッシュボードジョブモニタで確認することも、 E メール通知が送信されるまで待つこともできます。E メール通知の送信にかかる時間は、リストア処理が完了するまでの時間によって異なります。

+
通知 E メールには、リストア処理の出力が添付されます。リストア処理に失敗した場合は、追加情報の添付ファイルを開きます。


