---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: バックアップリソースグループを作成、変更、削除し、リソースグループに対してバックアップ処理を実行することができます。 
---
= リソースグループの管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
バックアップリソースグループを作成、変更、削除し、リソースグループに対してバックアップ処理を実行することができます。


NOTE: リソースグループは、 Virtual Storage Console （ VSC ）ではバックアップジョブと呼ばれます。



== リソースグループに対する処理の一時停止と再開

スケジュールされた処理を一時的に無効にして、リソースグループで開始されないように設定できます必要に応じて、あとからこれらの処理を有効にすることができます。

.手順
. SCVプラグインの左側のナビゲーションペインで、*[リソースグループ]*をクリックし、リソースグループを選択して*[中断]*をクリックします（または*[再開]*をクリックします）。
. 確認ボックスで、 * OK * をクリックして確定します。


.完了後
[ リソースグループ ] ページで ' 一時停止したリソースのジョブ・ステータスは 'Under_Maintenance' です必要に応じて、表を右にスクロールして [ ジョブステータス ] 列を表示します。

バックアップ・オペレーションが再開されると ' ジョブ・ステータスは本番に変わります



== リソースグループの変更

vCenter では、リソースグループ内のリソースを削除または追加したり、ポリシーを適用または適用解除したり、スケジュールを変更したり、その他のリソースグループオプションを変更したりすることができます。

.このタスクについて
リソースグループの名前を変更する場合は、 VM 、データストア、ポリシー、バックアップ、またはリソースグループの名前に次の特殊文字を使用しないでください。

%&*$#@ ！\ / ： * ？"<> - | ； ' 、。

アンダースコア文字（ _ ）を使用できます。

.手順
. SCVプラグインの左側のナビゲーションペインで、*[リソースグループ]*をクリックし、リソースグループを選択して*[編集]*をクリックします。
. [ リソースグループの編集 ] ウィザードの左側のリストで、変更するカテゴリをクリックし、変更を入力します。
+
複数のカテゴリで変更を行うことができます。

. [ 概要 ] ページが表示されるまで [ 次へ ] をクリックし、 [ 完了 ] をクリックします。




== リソースグループを削除する

リソースグループ内のリソースを保護する必要がなくなった場合は、 vCenter でリソースグループを削除することができます。SnapCenter Plug-in for VMware vSphere を vCenter から削除する前に、すべてのリソースグループが削除されていることを確認する必要があります。

.このタスクについて
リソースグループの削除処理は、すべて強制削除として実行されます。削除処理を実行すると、vCenterリソースグループからすべてのポリシーが解除され、リソースグループがSnapCenter Plug-in for VMware vSphereから削除され、リソースグループのすべてのバックアップとSnapshotが削除されます。


NOTE: SnapVault関係では、最新のSnapshotは削除できないため、リソースグループは削除できません。SnapVault関係の一部であるリソースグループを削除する場合は、事前にOnCommandシステムマネージャまたはONTAP CLIを使用してSnapVault関係を削除してから、最後のSnapshotを削除する必要があります。

.手順
. SCVプラグインの左側のナビゲーションペインで、*[リソースグループ]*をクリックし、リソースグループを選択して*[削除]*をクリックします。
. [ リソースグループの削除 *] 確認ボックスで、 [OK] をクリックして確定します。

