---
sidebar: sidebar 
permalink: scpivs44_restore_vms_from_backups.html 
keywords:  
summary: VMをリストアするときに、選択したバックアップコピーで既存の内容を上書きするか、VMのコピーを作成できます。 
---
= バックアップからのVMのリストア
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMをリストアするときに、選択したバックアップコピーで既存の内容を上書きするか、VMのコピーを作成できます。

VMは次の場所にリストアできます。

* 元の場所にリストア
+
** 元のESXiホストにマウントされている元のデータストア（元のVMは上書きされます）


* 別の場所へのリストア
+
** 元のESXiホストにマウントされている別のデータストア
** 同じvCenterで管理されている別のESXiホストにマウントされている元のデータストア
** 同じvCenterで管理されている別のESXiホストにマウントされている別のデータストア
** リンクモードの別のvCenterで管理されている別のESXiホストにマウントされている別のデータストア





NOTE: VVol VMを別のホストにリストアすることはできません。


NOTE: 次のリストアワークフローはサポートされていません。 Storage VM を追加してからその VM のバックアップを実行し、その Storage VM を削除してその Storage VM を含むクラスタを追加してから、元のバックアップのリストアを試みてください。


TIP: NFS環境でのリストア処理のパフォーマンスを向上させるには、VMwareアプリケーションのvStorage API for Array Integration（VAAI）を有効にします。

.開始する前に
* バックアップが存在している必要があります。
+
VMをリストアする前に、SnapCenter Plug-in for VMware vSphereを使用してVMのバックアップを作成しておく必要があります。

+

NOTE: SnapCenter Plug-in for VMware vSphere以外のソフトウェアで実行されたVMのSnapshotがあると、リストア処理を正常に完了できません。

* デスティネーションデータストアの準備が完了している必要があります。
+
** リストア処理のデスティネーションデータストアには、すべてのVMファイル（vmdk、vmx、vmsdなど）のコピーを格納できるだけの十分なスペースが必要です。
** デスティネーションデータストアに、以前のリストア処理の失敗で発生した古いVMファイルが含まれていないことを確認してください。古いファイルは名前形式です `restore_xxx_xxxxxx_<filename>`。


* VMは転送中ではありません。
+
リストアするVMがvMotionまたはStorage vMotionの状態でないことを確認します。

* HAコウセイエラア
+
バックアップを別の場所にリストアする前に、[vCenter ESXi Host Summary]画面にHA構成エラーが表示されていないことを確認してください。

* 別の場所へのリストア
+
** 別の場所にリストアする場合は、リストア処理のデスティネーションであるvCenterでSnapCenter Plug-in for VMware vSphereが実行されている必要があります。デスティネーションデータストアに十分なスペースが必要です。
** [Restore to alternate Location]フィールドでデスティネーションvCenterをDNSで解決できる必要があります。




.タスクの内容
* VMが登録解除され、再登録されました
+
VMのリストア処理を実行すると、元のVMの登録が解除され、バックアップSnapshotからVMがリストアされ、リストアされたVMが同じESXiサーバに同じ名前と設定で登録されます。リストア後に、VMをリソースグループに手動で追加する必要があります。

* データストアのリストア
+
データストアはリストアできませんが、データストア内のVMはリストアできます。

* VVol VMのリストア
+
** 複数のVMにまたがるVVOLデータストアはサポートされません。VMにまたがるVVOLデータストア内の接続されたVMDKはバックアップされないため、リストア後のVMには一部のVMDKのみが含まれます。
** VVOLを別のホストにリストアすることはできません。
** VVOLの自動リバランシングはサポートされていません。


* VMのVMware整合性スナップショットの失敗
+
VMのVMware整合性スナップショットが失敗した場合でも、VMはバックアップされます。バックアップコピーに格納されたエンティティはリストアウィザードで表示し、リストア処理に使用できます。

* VMが配置されているFabricPoolのストレージ階層を使用できない場合、リストア処理が失敗することがあります。


.手順
. VMware vSphere クライアント ユーザー インターフェイスで、ツールバーの *メニュー* を選択し、ドロップダウン リストから *VM とテンプレート* を選択します。
+

NOTE: 削除したVMをリストアする場合は、SnapCenter Plug-in for VMware vSphereに追加したStorage VMのクレデンシャルは、またはと同じ権限を持つユーザアカウントである必要があります `vsadmin` `vsadmin`。

. 左側のナビゲーションペインで、VMを右クリックし、ドロップダウンリストから* SnapCenter Plug-in for VMware vSphere *を選択し、2番目のドロップダウンリストから*リストア*を選択してウィザードを開始します。
. リストア*ウィザードの*[バックアップの選択]*ページで、リストアするバックアップSnapshotを選択します。
+
特定のバックアップ名またはバックアップ名の一部を検索するか、バックアップリストをフィルタすることができます。フィルタアイコンを選択し、日時の範囲、VMwareスナップショットを含むバックアップの有無、マウントするバックアップの有無、および場所を選択します。[OK]*を選択してウィザードに戻ります。

. [ スコープの選択 *] ページの [ リストア範囲 *] フィールドで [ 仮想マシン全体 *] を選択し、リストア先を選択して、バックアップをマウントするデスティネーション情報を入力します。
+
[* VM name *]フィールドで、同じVM名が存在する場合、新しいVM名の形式はになります `<vm_name>_<timestamp>`。

+
パーシャル・バックアップをリストアする場合、リストア処理では * Select Scope * ページがスキップされます。

. [ * 場所の選択 * ] ページで、リストアしたデータストアの場所を選択します。
+
SnapCenter Plug-in for VMware vSphere 4.5以降では、FlexGroupボリューム用のセカンダリストレージを選択できます。

. [概要]ページを確認し、*[完了]*を選択します。
. オプション：画面下部の*[最近のタスク]*を選択して、処理の進捗状況を監視します。
+
更新された情報を表示するには、画面を更新します。



.終了後
* IPアドレスの変更
+
別の場所にリストアした場合は、静的IPアドレスが設定されているときにIPアドレスが競合しないように、新しく作成したVMのIPアドレスを変更する必要があります。

* リストアしたVMをリソースグループに追加
+
VMはリストアされますが、以前のリソースグループに自動的に追加されることはありません。そのため、リストアしたVMを適切なリソースグループに手動で追加する必要があります。


