---
sidebar: sidebar 
permalink: scpivs44_detach_a_virtual_disk.html 
keywords:  
summary: 仮想ディスクを接続して個 々 のファイルをリストアしたら、親VMから仮想ディスクの接続を解除できます。 
---
= 仮想ディスクの接続解除
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
仮想ディスクを接続して個 々 のファイルをリストアしたら、親VMから仮想ディスクの接続を解除できます。

.手順
. VMware vSphere クライアント ユーザー インターフェイスで、ツールバーの *メニュー* を選択し、ドロップダウン リストから *VM とテンプレート* を選択します。
. 左側のナビゲーションペインで、VMを選択します。
. 左側のナビゲーションペインで、VMを右クリックし、ドロップダウンリストから* SnapCenter Plug-in for VMware vSphere *を選択し、2番目のドロップダウンリストから*仮想ディスクの接続解除*を選択します。
. [仮想ディスクの接続解除]*画面で、接続を解除するディスクを1つ以上選択し、*[選択したディスクの接続解除]*チェックボックスを選択して*[接続解除]*を選択します。
+

IMPORTANT: 正しい仮想ディスクを選択していることを確認してください。間違ったディスクを選択すると、本番環境の作業に影響することがあります

. オプション：「最近のタスク」セクションで処理の進捗状況を監視します。
+
更新された情報を表示するには、画面を更新します。

. 次の手順を実行して、仮想ディスクの接続が解除されたことを確認します。
+
.. ツールバーの*[メニュー]*を選択し、ドロップダウンリストから*[仮想マシンおよびテンプレート]*を選択します。
.. 左側のナビゲーションペインでVMを右クリックし、ドロップダウンリストから*[設定の編集]*を選択します。
.. [ 設定の編集 *] ウィンドウで、各ハードディスクのリストを展開してディスクファイルのリストを表示します。
+
[Edit Settings] ページには、 VM 上のディスクが一覧表示されます。各ハードディスクの詳細を展開して、接続されている仮想ディスクのリストを表示できます。




