---
sidebar: sidebar 
permalink: scpivs44_manage_policies.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere のバックアップポリシーを作成、変更、表示、適用解除、および削除できます。データ保護処理を実行するにはポリシーが必要です。 
---
= ポリシーを管理する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere のバックアップポリシーを作成、変更、表示、適用解除、および削除できます。データ保護処理を実行するにはポリシーが必要です。



== ポリシーを適用解除

リソースのデータ保護を管理するポリシーが不要となった場合は、 SnapCenter VMware プラグインリソースグループからポリシーの適用を解除できます。ポリシーを削除する場合や頻度を変更する場合は、事前にポリシーの適用を解除する必要があります。

SnapCenter VMware プラグインリソースグループからポリシーの適用を解除する場合のガイドラインは、 SnapCenter リソースグループの場合と異なります。VMware vSphere Web Client リソースグループではすべてのポリシーの適用を解除でき、その結果リソースグループにポリシーがない状態になります。ただし、そのリソースグループでデータ保護処理を実行するには、少なくとも 1 つのポリシーを適用する必要があります。

.手順
. VMware vSphere Web Client の左側の ［ Navigator ］ ペインで、 ［ * リソースグループ * ］ をクリックし、リソースグループを選択して ［ * 編集 * ］ をクリックします。
. リソースグループの編集ウィザードの * ポリシー * ページで、適用解除するポリシーの横にあるチェックマークをオフにします。
+
ポリシーのチェックマークをオンにすると、ポリシーがリソースグループに追加されます。

. ウィザードの残りの部分でリソースグループに追加の変更を加えてから、 [ 完了 ] をクリックします。




== ポリシーを変更する

SnapCenter Plug-in for VMware vSphere リソースグループのポリシーを変更することができます。リソースグループにポリシーが適用されている場合は、頻度、レプリケーションのオプション、 Snapshot コピーの保持の設定、またはスクリプトの情報を変更できます。

SnapCenter の VMware プラグインのバックアップポリシーを変更する処理は、 SnapCenter のアプリケーションベースのプラグインのバックアップポリシーを変更する場合とは異なります。プラグインポリシーを変更する場合は、リソースグループからポリシーの適用を解除する必要はありません。

レプリケーションまたは保持の設定を変更する前に、その影響を考慮する必要があります。

* レプリケーションまたは保持の設定を増やしています
+
新しい設定に達するまでバックアップが蓄積され続けます。

* レプリケーションまたは保持の設定を引き下げる場合
+
新しい設定を超過したバックアップは、次のバックアップの実行時に削除されます。




NOTE: SnapCenter VMware プラグインポリシーのスケジュールを変更するには、プラグインリソースグループでスケジュールを変更する必要があります。

.手順
. VMware vSphere Web Client の左側の ［ Navigator ］ ペインで、 ［ * Policies * ］ をクリックし、ポリシーを選択して ［ * Edit * ］ をクリックします。
. ポリシーのフィールドを変更します。
. 完了したら、 * アップデート * をクリックします。


変更は、スケジュールされたバックアップが次回実行されるときに有効になります。



== ポリシーを削除する

SnapCenter Plug-in for VMware vSphere 用に設定したバックアップポリシーが不要になった場合は、必要に応じて削除することができます。

SnapCenter の仮想アプライアンスを削除する前に、そのポリシーをすべてのリソースグループから解除しておく必要があります。

.手順
. VMware vSphere Web Client の左側の [Navigator （ナビゲーター） ] ペインで、 [* Policies （ポリシー） ] をクリックし、ポリシーを選択して、 [* Remove （削除） ] をクリックします。
. 確認ダイアログボックスで、 * OK * をクリックします。

