---
sidebar: sidebar 
permalink: scpivs44_manage_storage_systems.html 
keywords:  
summary: VMware vSphere Clientを使用してVMまたはデータストアをバックアップまたはリストアする前に、ストレージを追加する必要があります。 
---
= ストレージシステムを管理する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware vSphere Clientを使用してVMまたはデータストアをバックアップまたはリストアする前に、ストレージを追加する必要があります。



== Storage VMの変更

VMware vSphere Clientを使用して、SnapCenter Plug-in for VMware vSphereに登録されてVMのデータ保護処理に使用されるクラスタおよびStorage VMの設定を変更できます。

クラスタの一部として自動的に追加されたStorage VM（暗黙的なStorage VMと呼ばれることもあります）を変更すると、そのStorage VMは明示的なStorage VMに変更され、クラスタ内の残りのStorage VMを変更することなく個別に削除できます。証明書を使用した認証方式を使用している場合、[ストレージシステム]ページにユーザ名がN/Aと表示されます。ユーザ名はクラスタリスト内の明示的なStorage VMに対してのみ表示され、ExplicitSVMフラグがtrueに設定されています。すべてのStorage VMは、常に関連するクラスタの下に表示されます。


IMPORTANT: SnapCenterユーザー インターフェイスを使用してアプリケーション ベースのデータ保護操作用のストレージ VM を追加した場合は、同じユーザー インターフェイスを使用してそれらのストレージ VM を変更する必要があります。

.手順
. SCVプラグインの左側のナビゲータペインで、*[Storage Systems]*を選択します。
. [ストレージシステム]ページで、変更するStorage VMを選択し、*[編集]*を選択します。
. [ストレージシステムの編集]*ウィンドウで、新しい値を入力し、*[更新]*を選択して変更を適用します。




== Storage VMの削除

VMware vSphere Clientを使用して、vCenterのインベントリからStorage VMを削除できます。


NOTE: SnapCenterユーザー インターフェイスを使用してアプリケーション ベースのデータ保護操作用のストレージ VM を追加した場合は、同じユーザー インターフェイスを使用してそれらのストレージ VM を変更する必要があります。

.開始する前に
Storage VMを削除する前に、Storage VM内のすべてのデータストアをアンマウントする必要があります。

.タスクの内容
削除するStorage VM上のバックアップがリソースグループに含まれていると、そのリソースグループの以降のバックアップは失敗します。

.手順
. SCVプラグインの左側のナビゲータペインで、*[Storage Systems]*を選択します。
. [ストレージシステム]ページで、削除するStorage VMを選択し、*[削除]*を選択します。
. [ストレージシステムの削除]*確認ボックスで、*[ストレージシステムの削除]*のチェックボックスをオンにし、*[はい]*を選択して処理を確定します。*注：* ESXiホスト7.0U1以降のリリースのみがサポートされます。
+
link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["VMware vSphere Client Serviceを再起動します。"]です。


