---
sidebar: sidebar 
permalink: scpivs44_create_backup_policies_for_vms_and_datastores.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere を使用して VM とデータストアをバックアップするには、事前にバックアップポリシーを作成する必要があります。 
---
= VM とデータストアのバックアップポリシーの作成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere を使用して VM とデータストアをバックアップするには、事前にバックアップポリシーを作成する必要があります。

.作業を開始する前に
* 前提条件を確認しておく必要があります。
* セカンダリストレージの関係を設定しておく必要があります。
+
** Snapshotをミラーセカンダリストレージまたはバックアップセカンダリストレージにレプリケートする場合は、関係が設定されている必要があり、SnapCenter管理者がソースとデスティネーションの両方のボリューム用にStorage VMを割り当てておく必要があります。
** NFSまたはVMFSデータストア上のVersion-FlexibleMirror関係でSnapshotをセカンダリストレージに正常に転送するには、SnapMirrorポリシーのタイプがAsynchronous Mirrorであり、「all_source_snapshots」オプションがオンになっていることを確認します。
** セカンダリストレージ（mirror-vault）のSnapshot数が上限に達すると、バックアップ処理でバックアップを登録して保持を適用する処理が失敗し、次のエラーが表示されます。 `This Snapshot is currently used as a reference Snapshot by one or more SnapMirror relationships. Deleting the Snapshot can cause future SnapMirror operations to fail.`
+
この問題を解決するには、Snapshotの最大数に達しないようにセカンダリストレージのSnapMirror保持ポリシーを設定します。

+
管理者がユーザーにリソースを割り当てる方法については'を参照して https://docs.netapp.com/us-en/snapcenter/concept/concept_types_of_role_based_access_control_in_snapcenter.html["ロールベースアクセス制御の使用に関する SnapCenter 情報"^]ください



* VMと整合性のあるバックアップを作成する場合は、VMwareツールをインストールして実行する必要があります。VMを休止するにはVMwareツールが必要です。VM と整合性のあるバックアップは VVol VM ではサポートされません。
* SnapMirror Active Syncを使用すると、サイト全体に障害が発生してもビジネスサービスの運用を継続できるため、アプリケーションをセカンダリコピーを使用して透過的にフェイルオーバーできます。
+

NOTE: SnapMirrorアクティブ同期はVMFSデータストアでのみサポートされます。

+
SnapMirror Active Sync環境でVMFSデータストアを保護するには、SnapCenter管理者が次の作業を行う必要があります。

+
** テクニカルレポートの説明に従って、クラスタとメディエーターを設定します https://www.netapp.com/pdf.html?item=/media/21888-tr-4878.pdf["TR-4878：『SnapMirror active sync（formerly SMBC）』"]。
** VMFSデータストアに関連付けられているボリュームを整合性グループに追加し、2つのONTAPストレージシステム間に_AutomatedFailOver_or_AutomatedFailOverDuplex_protectionポリシーを使用してデータ保護関係を作成します。_AutomatedFailOverDuplex_policyは、ONTAP 9.15.1リリース以降でサポートされています。




.このタスクについて
ウィザードの各ページのフィールドのほとんどはわかりやすいもので、説明を必要としません。以下の手順では、説明が必要な一部のフィールドを取り上げます。

.手順
. SCVプラグインの左側のナビゲータペインで、*[Policies]*をクリックします。
. [ポリシー]*ページで、*[作成]*を選択してウィザードを開始します。
. [New Backup Policy] ページで、ポリシーを使用する vCenter Server を選択し、ポリシー名と概要を入力します。
+
** リンクモード
+
リンクモードでは、 vCenter ごとに個別の仮想アプライアンスがあります。そのため、 vCenter 間で名前の重複を使用できます。ただし、リソースグループと同じ vCenter 内にポリシーを作成する必要があります。

** サポートされない文字です
+
VM 、データストア、クラスタ、ポリシー、バックアップ、 またはリソースグループ名： %&*$#@ ！\ / ： * ？"<> - | ； ' 、。

+
アンダースコア文字（ _ ）を使用できます。



. 頻度の設定を指定します。
+
ポリシーではバックアップの頻度のみを指定します。バックアップの具体的なスケジュールは、リソースグループで定義します。したがって、複数のリソースグループで同じポリシーとバックアップ頻度を使用している場合でも、別々のバックアップスケジュールを設定できます。

. Snapshotロックを有効にするには、*[ロック期間]*チェックボックスを選択します。Snapshotのロック期間は、日/月/年として選択できます。
. 保持設定を指定します。
+

IMPORTANT: SnapVault レプリケーションを有効にする場合は、保持数を 2 以上に設定する必要があります。保持数を 1 バックアップに設定すると、保持処理が失敗することがあります。これは、新しいSnapshotがターゲットにレプリケートされるまで、最初のSnapshotがSnapVault関係の参照Snapshotになるためです。

+

NOTE: 最大保持数は、 ONTAP 9.4 以降のリソースでは 1018 のバックアップ、 ONTAP 9.3 以前のリソースでは 254 のバックアップです。保持期間を基盤となる ONTAP バージョンの値よりも大きい値に設定すると、バックアップが失敗します。これは、スパニングデータストアにも当てはまります。スパニングデータストアに ONTAP 9.3 以前と ONTAP 9.4 以降の両方のリソースが含まれている場合は、保持値を 254 に設定してください。

. [ * Replication * ] フィールドで、次の表に示すように、セカンダリ・ストレージへのレプリケーションのタイプを指定します。
+
|===
| フィールド名 | 操作 


| バックアップ後に SnapMirror を更新  a| 
プライマリバックアップボリュームとの SnapMirror 関係がある別のボリュームにバックアップセットのミラーコピーを作成する場合は、このオプションを選択します。ミラーバックアップ関係が設定されたボリュームでバックアップをミラーバックアップデスティネーションにコピーする場合は、「バックアップ後に SnapVault を更新」オプションのみを選択する必要があります。


NOTE: このオプションは、 SnapCenter Plug-in for VMware vSphere 4.5 以降の FlexGroup ボリュームのデータストアでサポートされます。


NOTE: SnapMirrorアクティブ同期構成でVMFSデータストアを保護するには、開始する前に_セクションに記載されている前提条件を満たし、*[バックアップ後にSnapMirrorを更新する]*を有効にする必要があります。



| バックアップ後に SnapVault を更新してください  a| 
プライマリバックアップボリュームとの SnapVault 関係がある別のボリュームでディスクツーディスクバックアップレプリケーションを実行する場合は、このオプションを選択します。


IMPORTANT: ボリュームに mirror-vault 関係が設定されている場合は、このオプションのみを選択する必要があります。


NOTE: このオプションは、 SnapCenter Plug-in for VMware vSphere 4.5 以降の FlexGroup ボリュームのデータストアでサポートされます。



| Snapshot ラベル  a| 
このポリシーで作成されたSnapVaultおよびSnapMirror Snapshotに追加するカスタムラベル（オプション）を入力します。
Snapshot ラベルは、このポリシーで作成された Snapshot をセカンダリストレージシステム上の他の Snapshot と区別する際に役立ちます。


NOTE: Snapshotラベルに使用できる文字数は最大31文字です。

|===
. オプション： ［ * 詳細設定 * ］ フィールドで、必要なフィールドを選択します。次の表に、 Advanced フィールドの詳細を示します。
+
|===
| フィールド名 | 操作 


| VM 整合性  a| 
バックアップジョブが実行されるたびに VM を休止して VMware スナップショットを作成する場合は、このチェックボックスをオンにします。

このオプションは VVOL に対してはサポートされていません。VVOL VM の場合は、 crash-consistent バックアップのみが実行されます。


IMPORTANT: VM整合性バックアップを実行するには、VMでVMware Toolsが実行されている必要があります。VMware toolsが実行されていない場合は、代わりにcrash-consistentバックアップが実行されます。


NOTE: VM 整合性ボックスをオンにすると、バックアップ処理に時間がかかり、より多くのストレージスペースが必要になる場合があります。このシナリオでは、 VM を最初に休止したあと、 VMware によって VM 整合性のある Snapshot が実行され、 SnapCenter によってバックアップ処理が実行されたあと、 VM の処理が再開されます。VM ゲストメモリは VM 整合性スナップショットに含まれません。



| 独立型ディスクのデータストアを含める | 一時的なデータを含む独立型ディスクのデータストアをバックアップに含める場合は、このチェックボックスをオンにします。 


| スクリプト  a| 
SnapCenter Plug-in for VMware vSphereでバックアップ処理の前後に実行するプリスクリプトまたはポストスクリプトの完全修飾パスを入力します。たとえば、SNMPトラップの更新、アラートの自動化、ログの送信を行うスクリプトを実行できます。スクリプトパスは、スクリプトの実行時に検証されます。


NOTE: プリスクリプトとポストスクリプトは仮想アプライアンス VM 上にある必要があります。複数のスクリプトを入力するには、スクリプトパスの入力後に * Enter キーを押し、スクリプトごとに改行します。セミコロンは使用できません。

|===
. [ * 追加 ] をクリックします。 *
+
ポリシーが作成されたことを確認し、ポリシーページでポリシーを選択してポリシーの設定を確認できます。


