---
sidebar: sidebar 
permalink: scpivs44_manage_the_vmware_vsphere_web_client_service.html 
keywords:  
summary: SnapCenter VMware vSphere Clientが正しく動作しない場合は、ブラウザキャッシュのクリアが必要になることがあります。問題が解決しない場合は、VMware vSphere Client Serviceを再起動します。 
---
= VMware vSphere Client Serviceを再起動します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter VMware vSphere Clientが正しく動作しない場合は、ブラウザキャッシュのクリアが必要になることがあります。問題が解決しない場合は、VMware vSphere Client Serviceを再起動します。



== Linux vCenter で Web Client Service を再起動します

Linuxアプライアンス上のvCenterでSnapCenter VMware vSphere Client Serviceを再起動するには、Linuxコマンドを使用する必要があります。

.作業を開始する前に
vCenter 6.5 以降が実行されている必要があります。

.手順
. SSH を使用して、 root として vCenter Server Appliance にログインします。
. 次のコマンドを使用して、 Appliance Shell または bash Shell にアクセスします。
+
「Shell」

. 次の HTML5 コマンドを使用して Web Client Service を停止します。
+
「 service-control 」 -- 「 vsphere-ui 」を停止します

. 次の HTML5 コマンドを使用して、 vCenter 上の古い scvm パッケージをすべて削除します。
+
`etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity/rm -rf com.netapp.scv.client-<version_number>`

+

IMPORTANT: VASAまたはvCenter 7.x以降のパッケージは削除しないでください。

. 次の HTML5 コマンドを使用して Web Client Service を開始します。
+
「 service-control -- start vsphere-ui 」を参照してください


