---
sidebar: sidebar 
permalink: scpivs44_restore_deleted_vms_from_backups.html 
keywords:  
summary: データストアのプライマリバックアップまたはセカンダリバックアップから削除した VM を、選択した ESXi ホストにリストアすることができます。 
---
= バックアップから削除した VM をリストアする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
データストアのプライマリバックアップまたはセカンダリバックアップから削除した VM を、選択した ESXi ホストにリストアすることができます。

VM は次の場所にリストアできます。

* 元の場所にリストアします
+
** を元の ESXi ホストにマウントされている元のデータストアに（ VM のコピーが作成されます）


* 別の場所にリストアします
+
** をリストアします
** を、同じ vCenter で管理されている別の ESXi ホストにマウントされている元のデータストアにコピーします
** 同じ vCenter で管理されている別の ESXi ホストにマウントされている別のデータストアに追加します
** リンクモードの別の vCenter で管理されている別の ESXi ホストにマウントされている別のデータストアに





NOTE: 別の場所にリストアする場合は、リストア処理のデスティネーションであるリンクされた vCenter で SnapCenter Plug-in for VMware vSphere が実行されている必要があります。デスティネーションデータストアに十分なスペースが必要です。


NOTE: 削除された VM のリストア時には、 VM に割り当てられていたタグやフォルダはリストアされません。

.作業を開始する前に
* ストレージシステムのユーザアカウントは、 VMware vSphere Web Client の Storage Systems ページで、に設定されている必要があります link:scpivs44_minimum_ontap_privileges_required.html["ONTAP に必要な最小限の ONTAP 権限"]。
* vCenter のユーザアカウントにが必要です link:scpivs44_minimum_vcenter_privileges_required.html["SnapCenter Plug-in for VMware vSphere に必要な最小限の vCenter 権限"]。
* バックアップが存在している必要があります。
+
その VM の VMDK をリストアする前に、 SnapCenter Plug-in for VMware vSphere を使用してその VM のバックアップを作成しておく必要があります。




TIP: NFS 環境でのリストア処理のパフォーマンスを向上させるには、 VMware アプリケーション vStorage API for Array Integration （ VAAI ）を有効にします。

データストアはリストアできませんが、データストア内の VM はリストアできます。

VM が配置されている FabricPool のストレージ階層が使用できない場合、リストア処理が失敗することがあります。

.手順
. [ * メニュー * ] をクリックし、 [ * ストレージ * ] メニュー・オプションを選択してから、データストアを選択し、 [ * 構成 * ] タブを選択して、 [ * SnapCenter Plug-in for VMware vSphere * ] セクションの [ * バックアップ * ] をクリックします。
. バックアップをダブルクリックして、バックアップに含まれるすべての VM のリストを表示します。
. バックアップ・リストから削除された VM を選択し、 * リストア * をクリックします。
. リストア * ウィザードの * バックアップの選択 * ページで、リストア元のバックアップ・コピーを選択します。
+
特定のバックアップ名またはバックアップ名の一部を検索するか、フィルタアイコンをクリックして日時の範囲、 VMware スナップショットの有無、マウントするバックアップの有無、および場所を選択して、バックアップリストをフィルタリングすることができます。[OK] をクリックしてウィザードに戻ります。

. [ スコープの選択 *] ページの [ リストア範囲 *] フィールドで [ 仮想マシン全体 *] を選択し、リストア先を選択して、バックアップをマウントするデスティネーション ESXi の情報を入力します。
+
リストア先には、 SnapCenter に追加されている任意の ESXi ホストを指定できます。このオプションは、指定した日時の Snapshot コピーから、 VM が配置されていた選択したバックアップの内容をリストアします。このオプションを選択して VM の電源をオンにすると、 * Restart VM * チェックボックスがオンになります。

+
NFS データストア内の VM を ESXi クラスタ内の別の ESXi ホストにリストアすると、リストア後、その VM が代替ホストに登録されます。

. ［ * 場所の選択 * ］ ページで、リストア元のバックアップ（プライマリまたはセカンダリ）の場所を選択します。
. [ 概要 ] ページを確認し、 [ 完了 ] をクリックします。

