---
sidebar: sidebar 
permalink: scpivs44_register_snapcenter_plugin_vmware_vsphere_with_snapcenter_server.html 
keywords:  
summary: SnapCenter（仮想化されたデータベースとファイルシステムのアプリケーションベースの保護ワークフロー）でVMDKを介したアプリケーションワークフローを実行する場合は、SnapCenter Plug-in for VMware vSphereをSnapCenter Serverに登録する必要があります。 
---
= SnapCenter Plug-in for VMware vSphereをSnapCenter Serverに登録
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter（仮想化されたデータベースとファイルシステムのアプリケーションベースの保護ワークフロー）でVMDKを介したアプリケーションワークフローを実行する場合は、SnapCenter Plug-in for VMware vSphereをSnapCenter Serverに登録する必要があります。

SnapCenterユーザがSnapCenter 4.2にアップグレードし、VMDK経由のアプリケーションバックアップをSnapCenter Plug-in for VMwareに移行した場合は、migrationコマンドによってプラグインが自動的に登録されます。

.開始する前に
* SnapCenterサーバ4.2以降を実行している必要があります。
* SnapCenter Plug-in for VMware vSphereを導入して有効にしておく必要があります。


.タスクの内容
* SnapCenter Plug-in for VMware vSphereをSnapCenter Serverに登録するには、SnapCenter GUIを使用して「vSphere」タイプのホストを追加します。
+
ポート8144は、SnapCenter Plug-in for VMware vSphere内の通信用に事前定義されています。

+
SnapCenter Plug-in for VMware vSphereの複数のインスタンスを同じSnapCenter Server 4.2に登録することで、VMでのアプリケーションベースのデータ保護処理をサポートできます。同じSnapCenter Plug-in for VMware vSphereを複数のSnapCenter Serverに登録することはできません。

* vCenterがリンクモードの場合は、vCenterごとにSnapCenter Plug-in for VMware vSphereを登録する必要があります。


.手順
. SnapCenter GUIの左側のナビゲーションペインで、*[ホスト]*を選択します。
. 上部で [Managed Hosts] タブが選択されていることを確認し、仮想アプライアンスのホスト名を見つけて、 SnapCenter サーバから解決されることを確認します。
. [追加]*を選択してウィザードを開始します。
. [Add Hosts] ダイアログ・ボックスで ' 次の表に示すように SnapCenter サーバに追加するホストを指定します
+
|===
| このフィールドでは… | 操作 


| ホストタイプ | ホストのタイプとして「 * vsphere * 」を選択します。 


| ホスト名 | 仮想アプライアンスのIPアドレスを確認します。 


| クレデンシャル | 導入時に指定したSnapCenter Plug-in for VMware vSphereのユーザ名とパスワードを入力します。 
|===
. [ 送信 ] を選択します。
+
追加されたVMホストは、[Managed Hosts]タブに表示されます。

. 左側のナビゲーションペインで、*[設定]*を選択し、*[クレデンシャル]*タブを選択し、*[追加]*を選択して仮想アプライアンスのクレデンシャルを追加します。
. SnapCenter Plug-in for VMware vSphereの導入時に指定したクレデンシャル情報を入力します。
+

NOTE: [Authentication]フィールドで[Linux]を選択する必要があります。



.終了後
SnapCenter Plug-in for VMware vSphereのクレデンシャルが変更された場合は、SnapCenterの[Managed Hosts]ページを使用してSnapCenterサーバでの登録を更新する必要があります。
