---
sidebar: sidebar 
permalink: scpivs44_minimum_vcenter_privileges_required.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere の導入を開始する前に、最小限必要な vCenter 権限があることを確認する必要があります。 
---
= 最小限の vCenter 権限が必要です
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere の導入を開始する前に、最小限必要な vCenter 権限があることを確認する必要があります。



== vCenter Admin ロールに必要な権限

Datastore.PowerLocateSpace Datastore.Browse Datastore.Delete Datastore.FileManagement Datastore.Move Extension.Register Extensionの更新Host.Config.AdvancedConfig Host.Config.Resources Host.Config.Config.Settings Host.Config.Config.Storage VirtualVirtualVirtualVirtualVirtualVMHost.Local.CreateVM Host.Local.DeleteVM Network.ReconfigVM Network.Assign Resource.Assign Resource.Assign Resource.Assign Resource.Assign Resource.Assign Resource.Assign Resource.Config.Assign Resource.Config.VM Resource.Config.VM Resource.Config.Config.Config.VM Resource.Config.VM Resource.Config.Datast.VM Resource.Config.Datast.Config.Datast.Datast.Datastoronymous仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンの仮想マシンのリソースのリソースの仮想マシンリソース



== SnapCenter Plug-in for VMware vCenter に固有の必要な権限

|===


| * 特権 * | *ラベル* 


| netappSCV。Guest。RestoreFile | ゲストファイルのリストア 


| netappSCV。Recovery).MountUnmount | mount / Unmount 


| SCV。Backup.DeleteBackupJobを指定します | リソースグループ/バックアップを削除します 


| netappSCV。Configure.ConfigureStorageSystems.Deleteの順にクリックします | ストレージシステムを削除 


| netappSCV。ビュー | 表示 


| SCV。リカバリ。RecoverVMを指定します | VMをリカバリします 


| netappSCV。Configure.ConfigureStorageSystems.AddUpdateを実行します | ストレージシステムを追加/変更 


| netappSCV。Backup.BackupNow | 今すぐバックアップする 


| netappSCV。Guest。設定 | ゲストの設定 


| netappSCV。Configure.ConfigureSnapCenterServerを実行します | SnapCenter サーバを設定します 


| 必要なバックアップスケジュールを設定します | リソースグループを作成します 
|===