---
sidebar: sidebar 
permalink: scpivs44_download_job_logs.html 
keywords:  
summary: ジョブログは、SnapCenter VMware vSphereクライアントのダッシュボードのジョブモニタタブからダウンロードできます。 
---
= ジョブログをダウンロードします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ジョブログは、SnapCenter VMware vSphereクライアントのダッシュボードのジョブモニタタブからダウンロードできます。

VMware vSphere Clientの使用中に予期しない動作が発生した場合は、ログファイルを使用して原因 を特定し、問題を解決できます。


NOTE: 保持ジョブのログのデフォルト値は 30 日で、保持ジョブのデフォルト値は 90 日です。設定した保持期間よりも古いジョブログとジョブは、 6 時間ごとにパージされます。Configurationのjobs/cleanup'REST APIを使用して'ジョブとジョブ・ログの保存期間を変更できますパージスケジュールは変更できません。

.手順
. vCenterクライアントのショートカットページで、SnapCenter Plug-in for VMware vSphere（SCV）を選択します。
. SCVの左側のナビゲーションペインで、*[ダッシュボード]*>*[ジョブモニタ]*を選択します。
. ジョブモニタのタイトルバーでダウンロードアイコンを選択します。
+
場合によっては、右にスクロールしないとアイコンが表示されないことがあります。

+
ジョブをダブルクリックして [ ジョブの詳細 ] ウィンドウにアクセスし、 [ ジョブログのダウンロード ] をクリックすることもできます。



.結果
ジョブログは、SnapCenter Plug-in for VMware vSphereが導入されているLinux VMホストに保存されます。デフォルトのジョブログの場所はです `/var/log/netapp`。

ジョブログをダウンロードしようとしたが、エラーメッセージに示された名前のログファイルが削除されている場合は、「 HTTP error 500 problem access/export-sv -logs 」というエラーが表示される可能性があります。このエラーを修正するには、という名前のファイルのファイルアクセスステータスと権限をエラーメッセージで確認し、アクセスの問題を修正します。
