---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflow__restore_vms.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere REST API を使用して VM バックアップのリストア処理を実行するには、規定された順序の REST API 呼び出しに従う必要があります。 
---
= VM をリストアするための REST API のワークフロー
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere REST API を使用して VM バックアップのリストア処理を実行するには、規定された順序の REST API 呼び出しに従う必要があります。

各 REST API について 'REST API の前面に https://<server>:<port>` を追加して ' 完全なエンドポイントを形成します

|===
| ステップ | REST API | コメント 


| 1. | http://<vCenter-IP>/mob` にアクセスします | VMware Managed Objects の URL から VM MORef を検索します。リストアする VM の * MORef * をメモします。 


| 2. | 「 /4.1/vm/{moref}/backups' 」と入力します | 「 VM バックアップの取得」は、指定された VM のバックアップのリストを取得します。手順 1 から * MORef * を渡します。リストアするバックアップの * backupid * をメモします。 


| 3. | `/4.1/vm/backups/{backupid}/snapshotlocations` | 'get snapshot locations' は ' 指定したバックアップの Snapshot コピーの場所を取得します手順 2 から * backupid * を渡します。この *snapshotsList* 情報に注意してください。 


| 4. | `/4.1/vm/{moref}/backups/availableesxhosts` | Get Available ESX Hosts （利用可能な ESX ホストの取得）は ' バックアップが保存されているホストの情報を取得します入手可能な EsxHostsList* 情報に注意してください。 


| 5. | `/4.1/vm/{moref}/backups/{backupid}/restore`  a| 
「バックアップから VM をリストア」を実行すると、指定したバックアップがリストアされます。ステップ 3 と 4 の情報を *restoreLocations* 属性に渡します


NOTE: VM のバックアップが部分的なバックアップの場合は、「 restartVM 」パラメータを「 false 」に設定します。


NOTE: テンプレートである VM はリストアできません。

|===