---
sidebar: sidebar 
permalink: scpivs44_manage_policies.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphereのバックアップポリシーを作成、変更、表示、適用解除、および削除できます。データ保護処理を実行するにはポリシーが必要です。 
---
= ポリシーの管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphereのバックアップポリシーを作成、変更、表示、適用解除、および削除できます。データ保護処理を実行するにはポリシーが必要です。



== ポリシーの適用解除

リソースのデータ保護を管理するポリシーが不要になった場合は、SnapCenter Plug-in for VMware vSphereリソースグループからポリシーの適用を解除できます。ポリシーを削除する前、またはスケジュール頻度を変更する前に、ポリシーの適用を解除する必要があります。

.タスクの内容
SnapCenter Plug-in for VMware vSphereリソースグループからポリシーの適用を解除するためのガイドラインは、SnapCenterリソースグループのガイドラインとは異なります。VMware vSphere Clientリソースグループの場合は、すべてのポリシーの適用を解除できます。その結果、リソースグループにポリシーがなくなります。ただし、そのリソースグループに対してデータ保護処理を実行するには、少なくとも1つのポリシーを適用する必要があります。

.手順
. SCVプラグインの左側のナビゲーションペインで、*[Resource Groups]*を選択し、リソースグループを選択して*[Edit]*を選択します。
. リソースグループの編集ウィザードの * ポリシー * ページで、適用解除するポリシーの横にあるチェックマークをオフにします。
+
ポリシーをチェックしてリソースグループにポリシーを追加することもできます。

. ウィザードの残りの部分でリソースグループに追加の変更を加え、*[終了]*を選択します。




== ポリシーの変更

SnapCenter Plug-in for VMware vSphereリソースグループのポリシーを変更できます。リソースグループにポリシーが適用されている場合は、頻度、レプリケーションオプション、Snapshotの保持設定、またはスクリプトの情報を変更できます。

.タスクの内容
SnapCenter Plug-in for VMware vSphereのバックアップポリシーの変更は、SnapCenterアプリケーションベースのプラグインのバックアップポリシーの変更とは異なります。プラグインのポリシーを変更するときに、リソースグループからポリシーの適用を解除する必要はありません。

レプリケーションまたは保持の設定を変更する前に、その影響を考慮する必要があります。

* レプリケーションまたは保持の設定を増やす
+
新しい設定に達するまでバックアップが蓄積され続けます。

* レプリケーションまたは保持の設定を引き下げる場合
+
新しい設定を超過したバックアップは、次のバックアップの実行時に削除されます。




NOTE: SnapCenter Plug-in for VMware vSphereポリシーのスケジュールを変更するには、プラグインリソースグループでスケジュールを変更する必要があります。

.手順
. SCVプラグインの左側のナビゲータペインで、*[Policies]*を選択し、ポリシーを選択して*[Edit]*を選択します。
. ポリシーのフィールドを変更します。
. 完了したら、*[更新]*を選択します。


変更は、スケジュールされたバックアップが次回実行されるときに有効になります。



== ポリシーの削除

SnapCenter Plug-in for VMware vSphere用に設定したバックアップポリシーが不要になった場合は、ポリシーを削除できます。

.開始する前に
SnapCenterを削除する前に、仮想アプライアンス内のすべてのリソースグループでポリシーの適用を解除しておく必要があります。

.手順
. SCVプラグインの左側のナビゲータペインで、*[Policies]*を選択し、ポリシーを選択して*[Remove]*を選択します。
. 確認ダイアログボックスで* OK *を選択します。

