---
sidebar: sidebar 
permalink: scpivs44_detach_a_virtual_disk.html 
keywords:  
summary: 仮想ディスクを接続して個々のファイルをリストアしたあとに、親 VM から仮想ディスクの接続を解除することができます。 
---
= 仮想ディスクを接続解除
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
仮想ディスクを接続して個々のファイルをリストアしたあとに、親 VM から仮想ディスクの接続を解除することができます。

.手順
. VMware vSphere Web Client の GUI で、ツールバーの * メニュー * をクリックし、ドロップダウンリストから * VMs and Templates * を選択します。
. 左側のナビゲーションペインで、 VM を選択します。
. 左側のナビゲーションペインで、 VM を右クリックし、ドロップダウンリストから * NetApp SnapCenter * を選択してから、セカンダリドロップダウンリストから * 仮想ディスクの接続解除 * を選択します。
. 仮想ディスクの接続解除 * 画面で、接続解除する 1 つまたは複数のディスクを選択し、選択したディスクの接続解除 * チェックボックスを選択して、 * 接続解除 * をクリックします。
+

IMPORTANT: 正しい仮想ディスクを選択していることを確認してください。間違ったディスクを選択すると、本番環境の作業に影響する可能性があり

. オプション：「最近のタスク」セクションで処理の進捗状況を監視します。
+
更新された情報を表示するには、画面を更新します。

. 次の手順を実行して、仮想ディスクの接続が解除されたことを確認します。
+
.. ツールバーの * メニュー * をクリックし、ドロップダウンリストから * VMS and Templates * を選択します。
.. 左側のナビゲーションペインで VM を右クリックし、ドロップダウンリストから * 設定の編集 * を選択します。
.. [ 設定の編集 *] ウィンドウで、各ハードディスクのリストを展開してディスクファイルのリストを表示します。
+
[Edit Settings] ページには、 VM 上のディスクが一覧表示されます。各ハードディスクの詳細を展開して、接続されている仮想ディスクのリストを確認できます。




