---
sidebar: sidebar 
permalink: scpivs44_restore_vms_from_backups.html 
keywords:  
summary: VM をリストアする際に、選択したバックアップコピーで既存の内容を上書きしたり、 VM のコピーを作成したりできます。 
---
= バックアップから VM をリストアする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VM をリストアする際に、選択したバックアップコピーで既存の内容を上書きしたり、 VM のコピーを作成したりできます。

VM は次の場所にリストアできます。

* 元の場所にリストアします
+
** を元の ESXi ホストにマウントされている元のデータストアに（元の VM が上書きされます）


* 別の場所にリストアします
+
** をリストアします
** を、同じ vCenter で管理されている別の ESXi ホストにマウントされている元のデータストアにコピーします
** 同じ vCenter で管理されている別の ESXi ホストにマウントされている別のデータストアに追加します
** リンクモードの別の vCenter で管理されている別の ESXi ホストにマウントされている別のデータストアに





NOTE: VVOL VMを別のホストにリストアすることはできません。


NOTE: 次のリストアワークフローはサポートされていません。 Storage VM を追加してからその VM のバックアップを実行し、その Storage VM を削除してその Storage VM を含むクラスタを追加してから、元のバックアップのリストアを試みてください。


TIP: NFS 環境でのリストア処理のパフォーマンスを向上させるには、 VMware アプリケーション vStorage API for Array Integration （ VAAI ）を有効にします。

.作業を開始する前に
* バックアップが存在している必要があります。
+
VMをリストアする前に、SnapCenter Plug-in for VMware vSphereを使用してVMのバックアップを作成しておく必要があります。

+

NOTE: SnapCenter Plug-in for VMware vSphere以外のソフトウェアで実行されたVMのSnapshotがあると、リストア処理を正常に完了できません。

* デスティネーションデータストアの準備が完了している必要があります。
+
** リストア処理のデスティネーションデータストアには、すべてのVMファイル（vmdk、vmx、vmsdなど）のコピーを格納できるだけの十分なスペースが必要です。
** 前回のリストア処理エラーで作成された古いVMファイルがデスティネーションデータストアに含まれていないことを確認してください。古いファイルの名前の形式は'restore_xxx_xxxxxx_<filename>`です


* VM が転送中でないことを確認する必要があります。
+
リストアする VM が vMotion または Storage vMotion の状態でないことを確認してください。

* HA 構成エラーです
+
バックアップを別の場所にリストアする前に、 vCenter ESXi Host Summary 画面に HA 構成のエラーが表示されていないことを確認します。

* 別の場所へのリストア
+
** 別の場所にリストアする場合は、リストア処理のデスティネーションとなる vCenter で SnapCenter Plug-in for VMware vSphere が実行されている必要があります。デスティネーションデータストアに十分なスペースが必要です。
** [Restore to alternate Location]フィールドのデスティネーションvCenterは、DNS解決可能でなければなりません。




.このタスクについて
* VM の登録が解除され、再登録されます
+
VMのリストア処理を実行すると、元のVMの登録が解除され、バックアップSnapshotからVMがリストアされ、リストアされたVMが同じESXiサーバに同じ名前と設定で登録されます。リストア後に、リソースグループに VM を手動で追加する必要があります。

* データストアのリストア
+
データストアはリストアできませんが、データストア内の VM はリストアできます。

* VVol VMのリストア
+
** VMにまたがるVVolデータストアはサポートされていません。VMにまたがるVVolデータストアに接続されたVMDKはバックアップされないため、リストアされたVMには一部のVMDKのみが含まれます。
** VVOLは別のホストにリストアすることはできません。
** VVolの自動リバランシングはサポートされていません。


* VM の VMware 整合性スナップショットの障害
+
VM の VMware 整合性スナップショットの作成に失敗した場合でも、 VM はバックアップされます。バックアップコピーに格納されたエンティティは、リストアウィザードで表示し、リストア処理に使用できます。

* VM が配置されている FabricPool のストレージ階層が使用できない場合、リストア処理が失敗することがあります。


.手順
. VMware vSphere ClientのGUIで、ツールバーの*メニュー*をクリックし、ドロップダウンリストから* VMs and Templates *を選択します。
+

NOTE: 削除したVMをリストアする場合は、SnapCenter Plug-in for VMware vSphereに追加したStorage VMのクレデンシャルは、またはと同じ権限を持つユーザアカウントである必要があります `vsadmin` `vsadmin`。ONTAP 8.2.2以降を実行しているストレージシステムにホストが配置されている必要があります。

. 左側のナビゲーションペインで、VMを右クリックし、ドロップダウンリストから* SnapCenter Plug-in for VMware vSphere *を選択し、2番目のドロップダウンリストから*リストア*を選択してウィザードを開始します。
. リストア*ウィザードの*[バックアップの選択]*ページで、リストアするバックアップSnapshotを選択します。
+
特定のバックアップ名またはバックアップ名の一部を検索するか、フィルタアイコンをクリックして日時の範囲、 VMware スナップショットの有無、マウントするバックアップの有無、および場所を選択して、バックアップリストをフィルタリングすることができます。[OK] をクリックしてウィザードに戻ります。

. [ スコープの選択 *] ページの [ リストア範囲 *] フィールドで [ 仮想マシン全体 *] を選択し、リストア先を選択して、バックアップをマウントするデスティネーション情報を入力します。
+
VM 名 * フィールドに同じ VM 名が存在する場合、新しい VM 名の形式は「 <vm_name>_ <timestamp> 」です。

+
パーシャル・バックアップをリストアする場合、リストア処理では * Select Scope * ページがスキップされます。

. [ * 場所の選択 * ] ページで、リストアしたデータストアの場所を選択します。
+
SnapCenter Plug-in for VMware vSphere 4.5 以降では、 FlexGroup ボリュームのセカンダリストレージを選択できます。

. [ 概要 ] ページを確認し、 [ 完了 ] をクリックします。
. オプション：画面下部の * 最近のタスク * をクリックして、処理の進行状況を監視します。
+
更新された情報を表示するには、画面を更新します。



.完了後
* IP アドレスを変更します
+
別の場所にリストアした場合は、静的 IP アドレスの設定時に IP アドレスの競合が発生しないように、新しく作成した VM の IP アドレスを変更する必要があります。

* リストアした VM をリソースグループに追加する
+
VM はリストアされますが、元のリソースグループに自動的に追加されることはありません。そのため、リストアした VM を適切なリソースグループに手動で追加する必要があります。


