---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_from_vmdks.html 
keywords:  
summary: WindowsゲストOSでは、VMDKから1つ以上のファイルまたはフォルダをリストアできます。 
---
= VMDKからのゲストファイルとフォルダのリストア
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
WindowsゲストOSでは、VMDKから1つ以上のファイルまたはフォルダをリストアできます。

.タスクの内容
デフォルトでは、接続されている仮想ディスクは24時間使用可能になり、その後自動的に接続解除されます。ウィザードで、復元操作が完了したときにセッションを自動的に削除するように選択するか、またはゲストファイルの復元セッションをいつでも手動で削除するか、または [*Guest Configuration*] ページで時間を延長することができます。

ゲストファイルまたはフォルダのリストアパフォーマンスは、リストアするファイルまたはフォルダのサイズと、リストアするファイルまたはフォルダの数という2つの要因によって決まります。リストア対象のデータセットのサイズが同じ場合、サイズの小さいファイルを多数リストアする場合は、サイズの小さいファイルを少数リストアする場合と比較して、想定よりも時間がかかることがあります。


IMPORTANT: 1つのVMで同時に実行できる接続処理またはリストア処理は1つだけです。同じVMに対して並行して接続処理またはリストア処理を実行することはできません。


IMPORTANT: ゲスト復元機能を使用すると、システムおよび隠しファイルの表示と復元、および暗号化されたファイルの表示を行うことができます。既存のシステムファイルを上書きしたり、暗号化されたファイルを暗号化されたフォルダに復元したりしないでください。リストア処理中、ゲストファイルの隠し属性、SYSTEM属性、および暗号化属性は、リストアされたファイルに保持されません。予約済みパーティションを表示または参照すると、エラーが発生することがあります。

.手順
. vSphere Clientのショートカットウィンドウで、*[ホストおよびクラスタ]*を選択し、VMを選択します。
. VMを右クリックし、* SnapCenter Plug-in for VMware vSphere *>*[Guest File Restore]*を選択します。
. [* リストア範囲 *] ページで、接続する仮想ディスクを含むバックアップを指定します。次の手順を実行します。
+
.. [* バックアップ名 * ] テーブルで、接続する仮想ディスクを含むバックアップを選択します。
.. * VMDK * テーブルで、リストアするファイルまたはフォルダが格納されている仮想ディスクを選択します。
.. [ * 場所 * ] テーブルで、接続する仮想ディスクの場所（プライマリまたはセカンダリ）を選択します。


. [*Guest Details*] ページで、次の操作を行います。
+
.. 仮想ディスクの接続先を選択します。
+
|===
| 選択するオプション | 条件 


| ゲストVMを使用  a| 
ウィザードを開始する前に右クリックした VM に仮想ディスクを接続し、右クリックした VM のクレデンシャルを選択します。


NOTE: VMのクレデンシャルを作成しておく必要があります。



| ゲストファイルリストアプロキシVMを使用  a| 
仮想ディスクをプロキシ VM に接続し、プロキシ VM を選択します。


NOTE: 接続とリストアの処理を開始する前に、プロキシVMを設定する必要があります。

|===
.. [ 電子メール通知を送信する *] オプションを選択します。
+
接続処理が完了し、仮想ディスクが使用可能になったときに通知を受け取るには、このオプションが必要です。通知Eメールには、仮想ディスク名、VM名、およびVMDKに新しく割り当てられたドライブレターが記載されています。

+

TIP: ゲストファイルのリストアは非同期処理であり、ゲストセッションの確立に時間がかかる可能性があるため、このオプションを有効にします。

+
このオプションでは、vCenterでVMware vSphere Clientをセットアップするときに設定されたEメール設定が使用されます。



. 概要を確認し、 [ 完了 ] をクリックします。
+
「 * 完了」をクリックする前に、ウィザードの任意のページに戻って情報を変更できます。

. 接続処理が完了するまで待ちます。
+
処理の進捗状況はダッシュボードのジョブモニタで確認できます。または、Eメール通知が表示されるまで待つこともできます。

. 接続されている仮想ディスクからリストアするファイルを検索するには、vSphere Clientのショートカットウィンドウで* SnapCenter Plug-in for VMware vSphere *を選択します。
. 左側のナビゲータペインで、*[Guest File Restore]*>*[Guest Configuration]*を選択します。
+
[Guest Session Monitor]テーブルで、[*...]*をクリックします。

. 通知メールに記載されている仮想ディスクのゲストファイルリストアセッションを選択します。
+
システムで予約されているパーティションを含め、すべてのパーティションにドライブ文字が割り当てられます。VMDKに複数のパーティションがある場合は、[Guest File Browse]ページの上部にあるドライブフィールドのドロップダウンリストでドライブを選択して、特定のドライブを選択できます。

. ファイルの参照 * アイコンをクリックして、仮想ディスク上のファイルとフォルダのリストを表示します。
+
フォルダをダブルクリックして個 々 のファイルを参照して選択すると、実行時にフェッチ操作が実行されるため、ファイルリストのフェッチ中に時間遅延が発生することがあります。

+
検索を簡単にするために、検索文字列にフィルタを使用できます。フィルタでは、スペースを含まないPerl式で大文字と小文字が区別されます。デフォルトの検索文字列は*です `.`。次の表に、Perlの検索式の例を示します。

+
|===
| この式 | 検索対象 ... 


| です。 | 改行文字以外の任意の文字。 


| * | 任意の文字列。これがデフォルトです。 


| A | 文字a。 


| AB | 文字列ab。 


| a [ 縦棒 ] b | 文字AまたはB。 


| A * | 文字aの0個以上のインスタンス。 


| A+ | 文字aの1つ以上のインスタンス。 


| A？ | 文字aの0または1つのインスタンス。 


| ｛ x ｝ | 文字aのインスタンスのx個の数を正確に指定します。 


| ｛ x 、 ｝ | 文字aのインスタンスの少なくともx個の数。 


| a ｛ x 、 y ｝ | 文字aのx個以上のインスタンスとy個以上のインスタンス。 


| \ | 特殊文字をエスケープします。 
|===
+
[Guest File Browse]ページには、他のすべてのファイルとフォルダに加えて、すべての隠しファイルとフォルダが表示されます。

. 復元する 1 つまたは複数のファイルまたはフォルダを選択し、 * リストア場所の選択 * をクリックします。
+
リストアするファイルとフォルダが[Selected File（s）]テーブルに一覧表示されます。

. [ リストア先の選択 *] ページで、次の項目を指定します。
+
|===
| オプション | 製品説明 


| パスへのリストア | 選択したファイルをリストアするゲストへのUNC共有パスを入力します。IPv4の例 `\\10.60.136.65\c$` ：IPv6の例： `\\fd20-8b1e-b255-832e--61.ipv6-literal.net\C\restore` 


| 元のファイルが存在する場合  a| 
リストア先にリストア対象のファイルまたはフォルダがすでに存在する場合に実行する処理を選択します。 Always overwrite または always skip 。


NOTE: フォルダがすでに存在する場合は、フォルダの内容が既存のフォルダにマージされます。



| リストアが正常に完了したら、ゲストセッションを切断します | このオプションは、リストア処理の完了時にゲストファイルのリストアセッションを削除する場合に選択します。 
|===
. [* リストア ] をクリックします。
+
リストア処理の進捗状況はダッシュボードのジョブモニタで確認できます。または、Eメール通知が表示されるまで待つこともできます。Eメール通知の送信にかかる時間は、リストア処理が完了するまでの時間によって異なります。

+
通知Eメールには、リストア処理の出力が添付されています。リストア処理が失敗した場合は、添付ファイルを開いて詳細情報を確認してください。


