---
sidebar: sidebar 
permalink: scpivs44_overview_of_different_snapcenter_guis.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphereは、他のSnapCenterプラグインとは異なるスタンドアロン プラグインです。VM、VMDK、およびデータストアのすべてのバックアップおよび復元操作には、vCenter の VMware vSphere クライアント ユーザー インターフェイスを使用する必要があります。 
---
= さまざまなSnapCenterユーザーインターフェースの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter環境では、適切なユーザー インターフェイスを使用してデータ保護および管理操作を実行する必要があります。

SnapCenter Plug-in for VMware vSphereは、他のSnapCenterプラグインとは異なるスタンドアロン プラグインです。VM、VMDK、およびデータストアのすべてのバックアップおよび復元操作には、vCenter の VMware vSphere クライアント ユーザー インターフェイスを使用する必要があります。また、Web クライアント ユーザー インターフェイス ダッシュボードを使用して、保護されている VM と保護されていない VM のリストを監視することもできます。バックアップと復元、ジョブ監視などのその他のすべてのSnapCenterプラグイン (アプリケーション ベースのプラグイン) 操作では、 SnapCenterユーザー インターフェイスを使用します。

VMとデータストアを保護するには、VMware vSphere Clientインターフェイスを使用します。Web クライアント ユーザー インターフェイスは、ストレージ システム上のNetAppスナップショット テクノロジと統合されます。これにより、VMやデータストアを数秒でバックアップし、ESXiホストをオフラインにすることなくVMをリストアすることが可能です。

SnapCenter Plug-in for VMware vSphereで管理操作を実行するための管理ユーザー インターフェイスもあります。

次の表は、 SnapCenterユーザー インターフェイスが実行する操作を示しています。

|===
| このユーザー インターフェースを使用します... | 実行する処理 | バックアップへのアクセス 


| SnapCenter vSphere クライアント ユーザー インターフェース | VM およびデータストアバックアップ VMDK を接続し、データストアマウントを接続解除して、 VM および VMDK リストアゲストファイルおよびフォルダのリストアをアンマウントします | VMware vSphere クライアント ユーザー インターフェイスを使用した VM およびデータストアのバックアップ。 


| SnapCenterユーザーインターフェース | VM上のデータベースとアプリケーションのバックアップとリストア（Microsoft SQL Server、Microsoft Exchange、Oracleのデータベースの保護など）データベースクローン | SnapCenterユーザー インターフェイスを使用して実行されるバックアップ。 


| SnapCenter Plug-in for VMware vSphere | ネットワーク設定の変更サポートバンドルの生成 NTP サーバ設定の変更プラグインを無効 / 有効にします | N/A 


| vCenter ユーザーインターフェース | vCenter Active Directory ユーザに SCV ロールを追加するユーザまたはグループにリソースアクセスを追加する | N/A 
|===
VM 整合性のあるバックアップおよび復元操作を行うには、VMware vSphere クライアント ユーザー インターフェイスを使用する必要があります。データストアのマウントや名前変更など、一部の処理はVMware Toolsを使用して実行できますが、これらの処理はSnapCenterリポジトリに登録されず、認識されません。

SnapCenter は、データベースと VM の単一スナップショットをサポートしていません。 VM とデータベースのバックアップは個別にスケジュール設定して実行する必要があり、データベースと VM が同じボリュームにホストされている場合でも個別のスナップショットが作成されます。アプリケーションベースのバックアップはSnapCenterユーザー インターフェイスを使用してスケジュールする必要があります。VM 整合性バックアップは VMware vSphere クライアント ユーザー インターフェイスを使用してスケジュールする必要があります。
