---
sidebar: sidebar 
permalink: scpivs44_rest_apis__download_jobs_and_generate_reports.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere REST APIを使用してVMware vSphere Clientジョブのレポートを生成し、ログをダウンロードするには、VMware vSphereのREST API呼び出しを使用する必要があります。 
---
= ジョブのダウンロードとレポートの生成に使用するREST API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere REST APIを使用してVMware vSphere Clientジョブのレポートを生成し、ログをダウンロードするには、VMware vSphereのREST API呼び出しを使用する必要があります。

各REST APIについて、REST APIの先頭にを追加し `\https://<server>:<port>` て完全なエンドポイントを形成します。



== ジョブの詳細情報を取得するには、[Jobs]セクションで次のREST APIを使用します。

|===
| REST API | コメント 


| `/4.1/jobs` | `Get all jobs` 複数のジョブのジョブの詳細を取得します。、、などのジョブタイプを指定することで、要求の範囲を絞り込むことができます `backup` `mountBackup` `restore`。 


| `/4.1/jobs/{id}` | `Get job details` 指定したジョブの詳細情報を取得します。 
|===


== [Jobs]セクションで次のREST APIを使用して、ジョブログをダウンロードします。

|===
| REST API | コメント 


| `/4.1/jobs/{id}/logs` | `getJobLogsById` 指定したジョブのログをダウンロードします。 
|===


== レポートを生成するには、[Reports]セクションで次のREST APIを使用します。

|===
| REST API | コメント 


| `4.1/reports/protectedVM` | `Get Protected VM List` 過去7日間に保護されたVMのリストを取得します。 


| `/4.1/reports/
unProtectedVM` | `Get Unprotected VM List` 過去7日間の保護されていないVMのリストを取得します。 
|===