---
sidebar: sidebar 
permalink: scpivs44_configure_credentials_for_vm_guest_file_restores.html 
keywords:  
summary: ゲストファイルまたはフォルダのリストア処理用に仮想ディスクを接続する場合は、リストア前に接続先のVMにクレデンシャルが設定されている必要があります。 
---
= VMゲストファイルのリストア用のクレデンシャルの設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ゲストファイルまたはフォルダのリストア処理用に仮想ディスクを接続する場合は、リストア前に接続先のVMにクレデンシャルが設定されている必要があります。

.タスクの内容
次の表に、ゲストリストア処理のクレデンシャル要件を示します。

|===
|  | ユーザアクセス制御が有効です | ユーザアクセス制御が無効になっています 


| ドメインユーザ | ユーザ名が「administrator」のドメインユーザは問題ありません。たとえば、「NetApp\administrator」と入力します。ただし、ローカル管理者グループに属するユーザ名が「xyz」のドメインユーザは機能しません。たとえば、「NetApp\xyz」は使用できません。 | ユーザ名が「administrator」のドメインユーザ、またはローカル管理者グループに属するユーザ名が「xyz」のドメインユーザはどちらでも問題ありません。たとえば、「NetApp\administrator」や「NetApp\xyz」などです。 


| ワークグループユーザ | ユーザ名が「administrator」のローカルユーザであれば問題ありません。ただし、ローカル管理者グループに属するユーザ名が「xyz」のローカルユーザは機能しません。 | ユーザ名が「administrator」のローカルユーザ、またはローカル管理者グループに属するユーザ名が「xyz」のローカルユーザはどちらでも問題ありません。ただし、ユーザ名が「xyz」で、ローカル管理者グループに属していないローカルユーザは機能しません。 
|===
上記の例では、「NetApp」はダミーのドメイン名、「xyz」はダミーのローカルユーザ名です。

.手順
. vSphere Clientのショートカットウィンドウで、[プラグイン]の*[ SnapCenter Plug-in for VMware vSphere ]*を選択します。
. 左側のナビゲーションで、*[ゲストファイルのリストア]*を選択します。
. Run As Credentials * セクションで、次のいずれかを実行します。
+
|===
| これを行うには ... | 操作 


| 既存のクレデンシャルを使用する | 設定されているクレデンシャルを選択します。 


| 新しいクレデンシャルを追加する  a| 
.. 「 * 追加」を選択します。
.. Run As Credentials * ダイアログボックスで、クレデンシャルを入力します。[Username]に「Administrator」と入力する必要があります。
.. [Select VM]*を選択し、*[Proxy VM]*ダイアログボックスでVMを選択します。[保存]*を選択して*[クレデンシャルとして実行]*ダイアログボックスに戻ります。クレデンシャルの認証に使用するVMを選択します。


|===
+
SnapCenter Plug-in for VMware vSphereは、選択したクレデンシャルを使用して、選択したVMにログオンします。

. [ 保存（ Save ） ] を選択します。

