---
sidebar: sidebar 
permalink: scpivs44_access_rest_apis_using_the_swagger_api_web_page.html 
keywords:  
summary: REST API は Swagger Web ページから利用できます。Swagger Web ページにアクセスして SnapCenter サーバまたは SnapCenter Plug-in for VMware vSphere REST API を表示したり、 API 呼び出しを手動で問題したりできます。SnapCenter Plug-in for VMware vSphere REST APIを使用して、VMとデータストアに対して保護処理を実行します。 
---
= Swagger API Web ページから REST API にアクセスします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
REST API は Swagger Web ページから利用できます。Swagger Webページにアクセスして、SnapCenter サーバまたはSnapCenter Plug-in for VMware vSphere REST APIを表示することも、API呼び出しを手動で問題 することもできます。SnapCenter Plug-in for VMware vSphere REST APIを使用して、VMとデータストアに対して処理を実行します。

プラグインには、SnapCenter Server Swagger Webページとは異なるSwagger Webページがあります。

.作業を開始する前に
SnapCenter Plug-in for VMware vSphere REST API の場合は、 SnapCenter VMware プラグインの IP アドレスまたはホスト名を確認しておく必要があります。


NOTE: このプラグインでは、サードパーティのアプリケーションと統合する目的で REST API のみがサポートされます。 PowerShell コマンドレットや CLI はサポートされません。

.手順
. ブラウザから、 URL を入力してプラグイン Swagger Web ページにアクセスします。
+
`https://<SCV_IP>:8144/api/swagger-ui/index.html`

+

IMPORTANT: REST API URL には、 + 、を使用しないでください。、 % 、および & 。

+
.例
SnapCenter VMware プラグイン REST API にアクセスします。

+
`https://<SCV_IP>:8144/api/swagger-ui/index.html`
`https://OVAhost:8144/api/swagger-ui/index.html`

+
ログインvCenter認証メカニズムを使用してトークンを生成します。

. API リソースタイプをクリックすると、そのリソースタイプの API が表示されます。

