---
sidebar: sidebar 
permalink: scpivs44_post-migration.html 
keywords:  
summary: バックアップメタデータを SnapCenter Plug-in for VMware vSphere に移行したあとに問題が発生することがあります。 
---
= 移行後
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
バックアップメタデータを SnapCenter Plug-in for VMware vSphere に移行したあとに問題が発生することがあります。

* 移行ログバンドル
+
SnapCenter インストールフォルダの 'App_Data/MigrationLog' ディレクトリから移行ログバンドルをダウンロードします移行が正常に完了したことが確認されるまで、移行ログバンドルを保持しておきます。

* ジョブの詳細はダッシュボードに表示されます
+
移行されたバックアップの情報は VMware vSphere Web Client の最近のジョブペインに表示されますが、移行後にバックアップが実行されるまで詳細情報はダッシュボードに表示されません。

* 認証エラー
+
Admin クレデンシャルを使用しないと、認証エラーが発生する場合があります。

+
link:scpivs44_manage_authentication_errors.html["認証エラーを管理します"]

* バックアップ名
+
移行前のバックアップ名の形式は RGName`_HOSTNAME_Timestamp` ですたとえば、「 -nas_ds_rG_perf1server_07-05-2019_02.11.59.9338 」のようになります。

+
移行後のバックアップ名の形式は 'RGName_Timestamp' です

+
たとえば、「 -nas_vm_RG_07-07-20_21.20.00.0609` 」のようになります。

* プリスクリプトとポストスクリプト
+
リソースグループに対して設定されているスクリプトは移行されません。Windows システム用に作成されたスクリプトは Linux ベースの仮想アプライアンスでは実行されない場合があるため、スクリプトのすべてまたは一部を再作成し、移行後にスクリプトを追加しなければならない場合があります。たとえば、 Windows のファイルパスは Linux には存在せず、「 .bat 」バッチファイルの呼び出しは Linux では機能しません。

+
1 つの解決策では、既存の Windows ベースのスクリプトを Linux ベースの仮想アプライアンスに配置し、スクリプトが変更なしで動作するかどうかをテストします。正しく動作しない場合は、スクリプト内の各 Windows ベースのコマンドを、対応する Linux 互換コマンドに置き換えてください。

* ゲストファイルのリストアクレデンシャル
+
ゲストファイルのリストアクレデンシャルは移行されません。そのため、移行後に新しいゲストファイルクレデンシャルを作成する必要があります。

* 'cbr.override' 設定ファイル
+
設定ファイル「 CBR 上書き」でカスタマイズした場合は、そのファイルを SnapCenter VMware プラグイン仮想アプライアンスに移動し、 Web Client Service を再起動する必要があります。

* SnapCenter アプリケーションベースのプラグインをアップグレードする
+
SnapCenter VMware プラグインを使用して他の SnapCenter プラグインをサポートしている場合は、それらのプラグインを 4.2 以降に更新する必要があります。

* SnapCenter サーバをアンインストールします
+
SnapCenter を VM と整合性のあるデータ保護または crash-consistent データ保護のみに使用する場合は、すべての VM のバックアップを SnapCenter VMware プラグインに移行したあとに、 Windows ホスト上の SnapCenter Server をアンインストールできます


