---
sidebar: sidebar 
permalink: scpivs44_guest_file_restore_scenarios_you_might_encounter.html 
keywords:  
summary: ゲストファイルをリストアしようとすると、ゲストファイルのリストアセッションが空白になったり、ゲストファイルのリストア接続ディスクの処理が失敗したり、ゲストファイルのリストアセッションが終了したあとにバックアップが切断されない場合があります。 
---
= ゲストファイルのリストアシナリオが発生する場合があります
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ゲストファイルをリストアしようとすると、次のいずれかの状況になることがあります。



== ゲストファイルリストアセッションが空白です

この問題は、ゲストファイルのリストアセッションを作成し、そのセッションがアクティブな間にゲストオペレーティングシステムをリブートしたときに発生します。この場合、ゲスト OS の VMDK はオフラインのままになります。したがって、ゲストファイルの復元セッションを参照しようとすると、リストは空白になります。

問題を修正するには、ゲスト OS で VMDK を手動でオンラインに戻します。VMDK がオンライン状態になると、ゲストファイルのリストアセッションに正しい内容が表示されます。



== ゲストファイルのリストアの接続ディスク処理が失敗する

この問題は、ゲストファイルのリストア操作を開始したときに発生しますが、 VMware Tools が実行されていてゲスト OS のクレデンシャルが正しいにもかかわらず、接続ディスク操作が失敗します。この場合、次のエラーが返されます。

「ゲストの資格情報の検証中にエラーが発生しました。指定された資格情報を使用してゲストシステムにアクセスできませんでした。システム上で VMware ツールが正しく実行されていること、使用されているアカウントが Administrator アカウントであることを確認してください。エラーは SystemError VIX エラーコード =(3016

問題を修正するには、ゲスト OS で VMware Tools Windows サービスを再起動してから、ゲストファイルのリストア操作を再試行します。



== ゲストの電子メールに？？？？？？？？？？？？？？を入力します

この問題は、ゲストファイルのリストア機能を使用して、名前に英語以外の文字が含まれているファイルやフォルダをリストアし、 E メール通知に「？？？？？？？？？？？？？？？？ " をクリックします。電子メールの添付ファイルには、復元されたファイルとフォルダの名前が正しく表示されます。



== ゲストファイルのリストアセッションを終了しても、バックアップの接続は解除されません

この問題は、 VM と整合性のあるバックアップからゲストファイルのリストア処理を実行した場合に発生します。ゲストファイルのリストアセッションがアクティブな間に、同じ VM に対して VM と整合性のある別のバックアップが実行されます。ゲストファイルのリストアセッションが、手動または 24 時間後に自動的に切断されても、セッションのバックアップは切断されません。

問題を修正するには、アクティブなゲストファイルリストアセッションから接続されていた VMDK の接続を手動で解除します。
