---
sidebar: sidebar 
permalink: scpivs44_concepts_overview.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere は、 VM とデータストアにデータ保護サービスを提供し、 SnapCenter アプリケーションベースのプラグインのデータ保護サービスをサポートする、スタンドアロンの仮想アプライアンス（オープン仮想アプライアンス形式）です。このドキュメントでは、 SnapCenter Plug-in for VMware vSphere を導入して使用する方法について説明します。また、クイックスタート情報も記載しています。 
---
= 製品の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]
:revnumber: 
:revdate: and supports data protection services for SnapCenter application-based plug-ins. This document describes how to deploy and use SnapCenter Plug-in for VMware vSphere and includes quick start information.


SnapCenter Plug-in for VMware vSphere は、 Linux ベースの仮想アプライアンスとして導入されます。

SnapCenter Plug-in for VMware vSphereは、環境に次の機能を追加します。

* VM と整合性のある crash-consistent データ保護処理がサポートされます。
+
vCenterのVMware vSphere Client GUIを使用して、VMware仮想マシン（従来のVMおよびVVOL VM）、VMDK、およびデータストアのバックアップとリストアのすべての処理を実行できます。VVOL VM （ VVOL データストア内の VM ）の場合は、 crash-consistent バックアップのみがサポートされます。また、 VM や VMDK をリストアしたり、ゲスト OS 上にあるファイルやフォルダをリストアしたりすることもできます。

+
VM 、 VMDK 、およびデータストアのバックアップ時には、プラグインで RDM がサポートされません。VM のバックアップジョブでは RDM は無視されます。RDM をバックアップする必要がある場合は、 SnapCenter アプリケーションベースのプラグインを使用する必要があります。

+
SnapCenter Plug-in for VMware vSphereには、SnapCenter Plug-in for VMware vSphereのメタデータを含むMySQLデータベースが含まれています。VM整合性およびクラッシュ整合性のあるデータ保護を実現するには、SnapCenterサーバをインストールする必要はありません。

* アプリケーションと整合性のある（ VMDK / RDM 経由のアプリケーション）データ保護処理がサポートされます。
+
SnapCenter GUI と適切な SnapCenter アプリケーションプラグインを使用して、 VM のプライマリストレージとセカンダリストレージ上のデータベースおよびファイルシステムのバックアップ処理とリストア処理をすべて実行できます。

+
SnapCenterは、SnapCenter Plug-in for VMware vSphereを標準で活用して、VMDK、rawデバイスマッピング（RDM）、NFSデータストア上のすべてのデータ保護処理を実行します。仮想アプライアンスの導入後は、vCenterとのやり取りがすべてプラグインで処理されます。SnapCenter Plug-in for VMware vSphereは、SnapCenterのアプリケーションベースのプラグインをすべてサポートしています。

+
SnapCenterでは、データベースとVMのシングルSnapshotを同時に作成することはできません。VMとデータベースのバックアップは、スケジュールを設定して個別に実行する必要があります。これにより、データベースとVMが同じボリュームでホストされている場合でも、個別のSnapshotが作成されます。SnapCenter GUIを使用してデータベースアプリケーションのバックアップのスケジュールを設定し、VMware vSphere Client GUIを使用してVMとデータストアのバックアップのスケジュールを設定します。

* VMと整合性のあるSnapshotにはVMwareツールが必要
+
VMwareツールがインストールされておらず、実行されていない場合、ファイルシステムは休止されず、crash-consistent Snapshotが作成されます。

* SAN （ VMFS ）環境でのリストア処理には、 VMware Storage vMotion が必要です
+
VMware ファイルシステム（ VMFS ）のリストアワークフローでは、 VMware Storage vMotion 機能を使用します。Storage vMotion は vSphere Standard ライセンスに含まれていますが、 vSphere Essentials または Essentials Plus ライセンスでは使用できません。

+
NFS 環境でのリストア処理のほとんどは、ネイティブの ONTAP 機能（ Single File SnapRestore など）を使用するため、 VMware Storage vMotion は必要ありません。

* VMware VVOL VMを設定するには、ONTAP Tools for VMware vSphereが必要です。
+
ONTAP ツールを使用して、ONTAP およびVMware Web ClientでVVOLのストレージをプロビジョニングおよび設定します。

+
詳細については、を参照してください。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["VMware vSphere 用の ONTAP ツール"^]

* SnapCenter Plug-in for VMware vSphereをLinux VMの仮想アプライアンスとして導入
+
仮想アプライアンスはLinux VMとしてインストールする必要がありますが、SnapCenter Plug-in for VMware vSphereではWindowsベースとLinuxベースの両方のvCenterがサポートされます。SnapCenterは、このプラグインを標準で使用します。ユーザの介入は必要ありません。vCenterと通信し、WindowsおよびLinuxの仮想アプリケーションに対してデータ保護処理を実行するSnapCenterアプリケーションベースのプラグインをサポートします。



SnapCenter Plug-in for VMware vSphereは、これらの主要な機能に加えて、iSCSI、ファイバチャネル、FCoE、NFS 3.0/4.1、VMFS 5.0/6.0、 NVMe over TCPをサポートします。

サポートされるバージョンの最新情報については、（IMT）を参照して https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^] ください。

NFSプロトコルとESXiホストについては、VMwareが提供するvSphere Storageのドキュメントを参照してください。

SnapCenterのデータ保護の詳細については、のSnapCenterプラグインのデータ保護に関する情報を参照して http://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter のドキュメント"^]ください。

サポートされるアップグレードパスと移行パスについては、を参照してください link:scpivs44_release_notes.html["『 SnapCenter Plug-in for VMware vSphere リリースノート』"^]。
