---
sidebar: sidebar 
permalink: scv48_audit_logs.html 
keywords:  
summary: 監査ログでは、誰がいつどのような行動をしたかを追跡できます。監査ログは、イベントを時間順にまとめたものであり、アプライアンス内のファイルに書き込まれます。 
---
= 監査ログ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
監査ログは、イベントを時間順にまとめたもので、アプライアンス内のファイルに書き込まれます。監査ログファイルは、に生成されます `/var/log/netapp/audit` 場所とファイル名は、次のいずれかの命名規則に従っています。

* audit.log：使用中のアクティブな監査ログファイルです。
* 監査-%d｛yyyy-mm-dd-HH - mm -ss｝。log.gz：監査ログファイルをロールオーバーします。ファイル名に含まれる日時は、ファイルが作成された日時を示します。例：audit-2022 -12-15-16-28-01-log.gz


SCVプラグインユーザインターフェイスでは、* Dashboard *>* Settings *>* Audit Logs *タブから監査ログの詳細を表示およびエクスポートできます。監査ログの処理の監査は、監査ログで確認できます。監査ログは、サポートバンドルを使用してダウンロードされます。

Eメールが設定されている場合、SCVは監査ログ整合性検証に失敗したときにEメール通知を送信します。監査ログ整合性検証のエラーは、ファイルの1つが改ざんまたは削除されたときに発生する可能性があります。

監査ファイルのデフォルトの設定は次のとおりです。

* 使用中の監査ログファイルは最大で10MBまで拡張できます
* 最大10個の監査ログファイルが保持されます


デフォルト設定を変更するには、/opt/netapp/scvservice/standalone _aegis /etc/scbr/ scbr.propertiesにキー値のペアを追加し、scvserviceを再起動します。

監査ログファイルの設定は次のとおりです。

* <xx> 。xxは監査ログファイルのロールオーバーの最大数です。例：auditMaxROFiles=15。
* auditLogSize =<XX> MB。xxはMB単位のファイルのサイズです。例：auditLogSize = 15MB。


ロールオーバーされた監査ログは、定期的に整合性が検証されます。SCVは、ログを確認して整合性を検証するためのREST APIを提供します。組み込みのスケジュールがトリガーされ、次のいずれかの整合性ステータスが割り当てられます。

|===


| ステータス | 説明 


| 改ざんされた | 監査ログファイルの内容が変更されました 


| 正常 | 監査ログファイルは変更されていません 


| ロールオーバー削除 | *監査ログ・ファイルは保存期間に基づいて削除されます*デフォルトでは10ファイルのみが保持されます 


| 予期しない削除です | 監査ログファイルが削除されました 


| アクティブ | *監査ログファイルは使用中です* audit.logにのみ適用されます 
|===
イベントは、次の3つの主要カテゴリに分類されます。

* データ保護イベント
* メンテナンスコンソールイベント
* Admin Consoleイベント




== データ保護イベント

SCVのリソースは次のとおりです。

* ストレージシステム
* リソースグループ
* ポリシー
* バックアップ


次の表に、各リソースに対して実行できる操作を示します。

|===


| リソース | 処理 


| ストレージシステム | 作成済み、変更済み、削除済み 


| リソースグループ | 作成、変更、削除、一時停止、再開 


| ポリシー | 作成済み、変更済み、削除済み 


| バックアップ | 作成、名前変更、削除、マウント、アンマウント、VMDK、リストアされたVM、VMDKの接続、VMDKの切断、ゲストファイルのリストアをリストア 
|===


== メンテナンスコンソールイベント

メンテナンスコンソールでの管理操作が監査されます。使用可能なメンテナンスコンソールのオプションは次のとおりです。

. サービスを開始/停止します
. ユーザ名とパスワードを変更します
. MySQLパスワードを変更します
. MySQLバックアップを設定します
. MySQLバックアップをリストアします
. 「 maint 」ユーザのパスワードを変更します
. タイムゾーンを変更します
. NTPサーバを変更します
. SSHアクセスを無効にします
. jailディスクサイズを拡張する
. アップグレード
. VMware Toolsのインストール（現在は、このツールをオープンVMツールに置き換えています）
. IP アドレスの設定を変更します
. ドメイン名検索設定を変更します
. 静的ルートを変更します
. 診断シェルにアクセスします
. リモート診断アクセスを有効にします




== Admin Consoleイベント

管理コンソールUIでは、次の操作が監査されます。

* 設定
+
** adminクレデンシャルを変更
** タイムゾーンを変更します
** NTPサーバを変更します
** IPv4/IPv6設定を変更します


* 設定
+
** vCenterクレデンシャルを変更します
** プラグインの有効化/無効化



