---
sidebar: sidebar 
permalink: scv48_audit_logs.html 
keywords:  
summary: 監査ログでは、誰がいつどのような行動をしたかを追跡できます。監査ログはイベントを時系列順に集めたもので、アプライアンス内のファイルに書き込まれます。 
---
= 監査ログ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
監査ログはイベントを時系列順に集めたもので、アプライアンス内のファイルに書き込まれます。監査ログファイルはで生成され `/var/log/netapp/audit` 、ファイル名は次のいずれかの命名規則に従います。

* audit.log：使用中のアクティブな監査ログファイルです。
* 監査-%d｛yyyy-mm-dd-HH - mm -ss｝。log.gz：監査ログファイルをロールオーバーします。ファイル名に含まれる日時は、ファイルが作成された日時を示します。例：audit-2022 -12-15-16-28-01-log.gz


SCVプラグインユーザインターフェイスでは、* Dashboard *>* Settings *>* Audit Logs *タブから監査ログの詳細を表示およびエクスポートできます。監査ログの処理の監査は、監査ログで確認できます。監査ログはサポートバンドルとともにダウンロードされます。

Eメールが設定されている場合は、監査ログの整合性検証に失敗した場合に、SCVからEメール通知が送信されます。監査ログ整合性検証エラーは、いずれかのファイルが改ざんまたは削除された場合に発生することがあります。

監査ファイルのデフォルトの設定は次のとおりです。

* 使用中の監査ログファイルは最大10MBまで拡張可能
* 最大10個の監査ログファイルを保持


ロールオーバーされた監査ログは定期的に整合性が検証されます。SCVには、ログを表示して整合性を検証するためのREST APIが用意されています。組み込みのスケジュールがトリガーされ、次のいずれかの整合性ステータスが割り当てられます。

|===


| ステータス | 製品説明 


| 改ざん | 監査ログファイルの内容の変更 


| 標準 | 監査ログファイルは変更されていません 


| ロールオーバー削除 | -監査ログファイルは保持に基づいて削除されます-デフォルトでは10個のファイルのみが保持されます 


| 予期しない削除 | 監査ログファイルが削除されました 


| アクティブ | -監査ログファイルが使用中です。audit.logにのみ適用されます。 
|===
イベントは、主に次の3つのカテゴリに分類されます。

* データ保護イベント
* メンテナンスコンソールイベント
* 管理コンソールイベント




== データ保護イベント

SCVのリソースは次のとおりです。

* ストレージシステム
* リソースグループ
* ポリシー
* バックアップ
* 配信登録
* アカウント


次の表に、各リソースで実行できる操作を示します。

|===


| * リソース * | * 操作 * 


| ストレージシステム | 作成、変更、削除 


| 配信登録 | 作成、変更、削除 


| アカウント | 作成、変更、削除 


| リソースグループ | 作成、変更、削除、一時停止、再開 


| ポリシー | 作成、変更、削除 


| バックアップ | 作成、名前変更、削除、マウント、アンマウント、 VMDKのリストア、VMのリストア、VMDKの接続、VMDKの接続解除、ゲストファイルのリストア 
|===


== メンテナンスコンソールイベント

メンテナンスコンソールでの管理操作が監査されます。メンテナンスコンソールで使用できるオプションは次のとおりです。

. サービスの開始/停止
. ユーザー名とパスワードの変更
. MySQLパスワードの変更
. MySQLバックアップの設定
. MySQLバックアップのリストア
. 「maint」ユーザのパスワードの変更
. タイムゾーンの変更
. NTPサーバの変更
. SSHアクセスの無効化
. jailディスクサイズの拡張
. アップグレード
. VMware Toolsのインストール（現在は、このツールをオープンVMツールに置き換えています）
. IPアドレス設定の変更
. ドメイン名検索設定の変更
. 静的ルートの変更
. 診断シェルへのアクセス
. リモート診断アクセスの有効化




== 管理コンソールイベント

Admin Console UIでは、次の操作が監査されます。

* 設定
+
** adminクレデンシャルを変更
** タイムゾーンの変更
** NTPサーバの変更
** IPv4/IPv6設定の変更


* 構成
+
** vCenterクレデンシャルの変更
** プラグインの有効化/無効化






== syslogサーバを設定します

監査ログはアプライアンス内に保存され、定期的に整合性が検証されます。イベント転送を使用すると、は、ソースコンピュータまたは転送コンピュータからイベントを取得し、一元化されたコンピュータ（Syslogサーバ）に保存できます。データは、ソースとデスティネーションの間で転送中に暗号化されます。

.開始する前に
管理者権限が必要です。

.タスクの内容
このタスクは、syslogサーバの設定に役立ちます。

.手順
. SnapCenter Plug-in for VMware vSphereにログインします。
. 左側のナビゲーションペインで、*[設定]*>*[監査ログ]*>*[設定]*を選択します。
. [監査ログ設定]*ペインで、*[監査ログをsyslogサーバに送信]*を選択します
. 次の詳細を入力します。
+
** syslogサーバのIP
** syslogサーバのポート
** RFC形式
** syslogサーバ証明書


. [保存]*をクリックして、syslogサーバの設定を保存します。




== 監査ログの設定を変更します

ログ設定のデフォルト構成を変更できます。

.開始する前に
管理者権限が必要です。

.タスクの内容
このタスクは、デフォルトの監査ログ設定を変更する場合に役立ちます。

.手順
. SnapCenter Plug-in for VMware vSphereにログインします。
. 左側のナビゲーションペインで、*[設定]*>*[監査ログ]*>*[設定]*を選択します。
. [監査ログ設定]*ペインで、監査ログファイルの最大数と監査ログファイルの最大サイズを入力します。
. ログをsyslogサーバに送信することを選択した場合は、*[Send audit logs to Syslog server]*オプションを選択します。サーバの詳細を入力します。
. 設定を保存します。

