---
permalink: scv_releasenotes_whats_new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, scv, 6.2' 
summary: SnapCenter Plug-in for VMware vSphereで利用できる新しい機能について説明します。 
---
= SnapCenter Plug-in for VMware vSphere 6.2の新機能
:allow-uri-read: 


[role="lead"]
SnapCenter Plug-in for VMware vSphereで利用できる新しい機能について説明します。

SnapCenter Plug-in for VMware vSphere 6.2 リリースでは、 ONTAP 9.17.1 以降を実行しているASA r2 システムの VMFS データストア上の仮想マシン (VM) のバックアップとリカバリのサポートが追加されました。このリリースでは、 ASA r2 システム上の VM、データストア、および仮想マシン ディスク (VMDK) 形式に対して次の操作を実行できます。

* プライマリ保護のための整合性グループのプロビジョニング
* 整合性グループベースのバックアップを実行する
* 階層的整合性グループを使用する（ ONTAP 9.17.1以降のバージョンで利用可能）
* クローンワークフローを実行する
* 復元ワークフローを実行する
* リソース グループの作成または変更時に二次保護をプロビジョニングする ( ONTAP 9.16.1 以降のバージョンで利用可能)


このリリースから、 SnapCenter Plug-in for VMware vSphereは、バージョン 9.10 以降を実行しているNetApp ONTAPストレージ システム用の Amazon FSxN をサポートします。

[NOTE]
====
SnapCenter Plug-in for VMwareからNetApp Backup and Recoveryへのシームレスでワンクリック、無停止の移行を実行できるようになりました。NetApp Backup and Recoveryは、次のような強化されたデータ保護および管理機能を提供します：

* 3-2-1バックアップおよびアーカイブ戦略のサポート
* SnapLockとオブジェクトロックを使用した論理的なエアギャップバックアップによるランサムウェア対策
* ランサムウェアスキャン中の自動修復
* セカンダリストレージおよびオブジェクトストレージターゲットの自動化されたSnapMirror関係の作成、合理化されたバックアップ保持管理、および簡素化されたアプリケーションおよびVMバックアップワークフロー
* データ量の増加に対応するための拡張性とパフォーマンスの向上
* 完全管理型のバックアップサービスにより、諸経費と総所有コストを削減できます。
* 単一のインターフェースから複数のvCenterインスタンスにわたるデータストアとVMの集中型バックアップ管理
* WindowsおよびLinuxゲストOSからのファイルとフォルダの迅速なリストア


====
詳細については、以下のリンクを参照してください：

* https://docs.netapp.com/us-en/data-services-backup-recovery/["NetApp Backup and Recovery ドキュメント"]。
* https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-discovery.html["NetApp Backup and Recoveryを使用したVMwareワークロードの検出"]
* https://docs.netapp.com/us-en/data-services-backup-recovery/br-start-login.html["NetApp Backup and Recoveryにログインします"]
* https://console.netapp.com/unified-backup-restore["NetApp Backup and Recoveryサービスにアクセスします"]




== NetApp Backup and Recoveryを使用してVMware環境を保護

video::UeT9yFssTug[youtube,width=848,height=480]